### ISSUE TITLE
zurück zu gemeinsamer Achse

### ISSUE THREAD

**Issue by csr-1-0** [ioBroker/ioBroker.echarts#11]
Hi,

wenn ich bei den Datenquellen eine eigene Achse wähle, kann ich nicht mehr zur gemeinsamen Achse zurück wechseln.

![Eigene_Achse](https://user-images.githubusercontent.com/60780818/100623089-f73f7300-3321-11eb-8ea0-64b20fbdc90b.jpg)

**Comment by csr-1-0** [comment]
Aktualisierung:

Anscheinend nur bei Importierten aus Flot so.

Bei neu angelegten Charts ist (bis jetzt ;-) ) alles gut.

**Comment by GermanBluefox** [comment]
Kann nicht reproduzieren. Hast du Aktions-Rehenfolge?
