### ISSUE TITLE
ECharts verursacht Fehler bei influxdb 2

### ISSUE THREAD

**Issue by DerDoubleD** [ioBroker/ioBroker.echarts#143]
**Describe the bug**  
Wenn ich ein EChart erzeuge das ale Quelle eine Influxdb2 hat wird nach kurzer Zeit ein Fehler im Log vom influxdb Adapter angezeigt.

> Error in query "from(bucket: "iobroker") |> range(start: 2021-08-17T14:00:00.000Z, stop: 2022-08-17T13:59:59.999Z) |> filter(fn: (r) => r["_measurement"] == "mqtt.0.SmartHome.Aussen.Wetterstation.get.wind_kmh") |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") |> group() |> sort(columns: ["_time"], desc: true) |> limit(n: 1)": RequestTimedOutError: Request timed out

Erzeuge ich das geiche Chart aus einer influxdb1.8 gibt es keine Probleme.

**Screenshots & Logfiles** 
![grafik](https://user-images.githubusercontent.com/47006370/185229593-243f37f2-30ad-48a8-9c5c-34a12ce2b39a.png)

**Versions:**  
 - Adapter version: 1.0.12
 - JS-Controller version: 
 - Node version: 14.20.0
 - Operating system: ubuntu

**Comment by Apollon77** [comment]
Das hat aber nichts mit dem Adapter zu tun sondern ggf eher mit deiner InfluxDB Installation.

Der Fehler hier ist ein Timeout ... bedeutet "beim schreiben hat die influxdb nicht geantwotet" - bz scheinbar auch schon beim lesen der Daten. Also Storage prüfen, InfluxDB log prüfen. ggf ist Sie durch eine "Query mit langem zeitraum" und langsamem  I/O und sowas überfordert.

**Comment by DerDoubleD** [comment]
Das dachte ich zuerst auch. Aber greife ich mit grafana oder über Javascript zu gibts keine Probleme. Auch bei sehr langen Anfragen.
Das Problem tritt nur auf wenn ich echart einsetzen will.
Deshalb liegt die Vermutung nahe das der Adapter doch was damit zu tun hat.

Kann ich irgend einen log zusätzlich einschalten um mehr Infos bereitstellen zu können?

**Comment by Apollon77** [comment]
Also wenn ist es nicht echarts sondern der influxdb adapter, da dieser die History Daten aus der DB selektiert. Setze doch da in der Konfig mal das timeout hoch
