### ISSUE TITLE
Ordner für IDs ist leer

### ISSUE THREAD

**Issue by horphi0815** [ioBroker/ioBroker.echarts#165]
Hallo zusammen,

ich bekomme keine Datenpunkte zum auswählen angezeigt.
![grafik](https://user-images.githubusercontent.com/39962016/190893749-44e65449-3592-40d4-99ec-c0e93d73a0ac.png)

Muss ich vorher noch Berechtigungen setzen?

Vielen Dank und Grüße

**Comment by sigi2345** [comment]
Hast du auch ein Preset erstellt?

**Comment by horphi0815** [comment]
> Hast du auch ein Preset erstellt und einen DP mit History aktiviert?

Danke dir. Das war das Problem. ;-)
Habe es jetzt hinbekommen. 
Viele Grüße
