### ISSUE TITLE
Permission denied when deleting a preset

### ISSUE THREAD

**Issue by axelhooge** [ioBroker/ioBroker.echarts#166]
Hi,

when i try to delete a preset, i get an error "permission denied". This happens in echart tab and also in the objects browser.
By renaming a preset, a new one is created with the new name and the old on remains unchanged. 

No relevant message occured in protocol tab.

I already tried to remove and reinstall echart.

**Comment by Apollon77** [comment]
Do you work with USers with limited rights?

**Comment by axelhooge** [comment]
No, logged in as "Admin"

**Comment by jr-ger** [comment]
Just installed echarts, same problem here.

Version v1.0.12

**Comment by bexmann** [comment]
Same problem here. What can I do to remove presets via cli?

**Comment by pparvin** [comment]
me to. delete and reinstall modules doesn't fix the problem.
v1.0.12

**Comment by uahrendt** [comment]
Same problem here: trying to rename/delete an entry as admin => "permission denied". 
V1.0.12

**Comment by pparvin** [comment]
I changed the version of the admin adapter to 6.2.12 and it works. It’s not a problem of the Eckarts adapter, because message also appears on other adapter.

**Comment by Apollon77** [comment]
Should be fixed by Admin 6.2.23 ((Beta, stable soon)
