### ISSUE TITLE
Scrollen und zoomen mit Fingern am Tablet teilweise ohne Funktion

### ISSUE THREAD

**Issue by obodeldog** [ioBroker/ioBroker.echarts#17]
das Scrollen in der Grafik mit Fingern auf Tablet ist sehr schwer, bei der Veränderung der Zeitachse mit zwei Fingern zieht sich das Gesamtbild groß oder klein, die Zeitachse reagiert nicht!

**Comment by Baenker** [comment]
das Problem habe ich auch. Sowohl im Browser als auch auf der ioBroker-App für ios. Aus dem Grund bleibe ich vorerst bei float.

**Comment by Baenker** [comment]
Mit der neuen Version 4.10 ist das Problem behoben. Ich werde jetzt komplett auf echart umsteigen.
