### ISSUE TITLE
Presets mit gleichen Namen in unterschiedlichen Ordnern nicht möglich

### ISSUE THREAD

**Issue by dp20eic** [ioBroker/ioBroker.echarts#18]
Hallo,

ich habe Ordner (Erdgeschoss, Obergeschoss u. Dachgeschoss) angelegt, und unterhalb ein "preset_1", soweit alles ok.

1. echarts.0.Dachgeschoss.preset_1
2. echarts.0.Erdgeschoss.preset_1
3. echarts.0.Obergeschoss.preset_1

Jetzt will ich z.B. die Luftfeuchtigkeiten der Etage mittels Diagramm darstellen und Speichern als
1. echarts.0.Dachgeschoss.Humidity

Wenn ich jetzt versuche das auch für das Obergeschoss zu machen kann ich das nicht Speichern als
3. echarts.0.Obergeschoss.Humidity

Da der Name "Humidity" gleich ist.
Das ist meiner Meinung nach ein Fehler, da sich ja das "preset -> Humidity" in verschiedenen Ordnern / Ebenen befindet,

echarts.0
   Etage(EG, OG, DG)
        preset(Humidity)

Sobald ich den Namen des "presets" ändere kann ich es auch abspeichern.

P.S.: klasse Arbeit, was Du und die anderen hier leistet.

**Comment by GermanBluefox** [comment]
Please test 0.4.6

**Comment by dp20eic** [comment]
> Please test 0.4.6

Hi, habe es gerade versucht, leider noch das gleiche Problem, ich kann in den Unterordnern keine presets mit gleichem Namen anlegen.

![image](https://user-images.githubusercontent.com/71387331/102008521-8d679600-3d31-11eb-8aaf-7046748d1647.png)

Ich habe den upload gemacht, Adapter neu gestartet, alle Objekte gelöscht und neu angelegt, nachdem ich den Ordner erstellt habe und das erste preset "preset_1" angelegt habe, sind auch unterhalb des Ordners die Objekte mit dem gleichen Namen angelegt.

![image](https://user-images.githubusercontent.com/71387331/102009405-7a57c480-3d37-11eb-94f7-f84091aacf94.png)


danach kann ich auch die Werte aus den Instanzen (zigbee) (xaomi) in ein Chart einfügen und speichern unter preset_1 aber das Umbenennen geht nicht siehe erstes Bild.

**Comment by GermanBluefox** [comment]
Das Problem ist dieses Objekt:
![image](https://user-images.githubusercontent.com/4582016/102018231-65e1ef00-3d6c-11eb-9ef6-55a30271f714.png)

Wenn du `function(doc) { if (doc.type === 'chart') emit(doc.common.name, doc); }` auf
`function(doc) { if (doc.type === 'chart') emit(doc._id, doc); }`

änderst, dann wird alles gehen. Warum das Objekt bei dir sich nicht upgedatet hat, dass kann ich nicht verstehen, da beim start von iobroker.echarts das getan werden muss.
