### ISSUE TITLE
Ladedauer ist sehr lange...

### ISSUE THREAD

**Issue by Starter4711** [ioBroker/ioBroker.echarts#187]
Hi,
Ich verwende echarts dankenswerterweise bei allen meinen grafischen Anzeigen.
Seit den letzten Updates (ich kann nicht genau sagen, seit wann es angefangen hat), ist das Laden teils Minutenlang.
Node.js v14.20.0
js 4.0.23
v 6.2.22
echarts 1.0.12
Macbook, iPhone, verbunden per WLan. 
<img width="1087" alt="Bildschirmfoto 2022-10-08 um 07 10 02" src="https://user-images.githubusercontent.com/15359915/194690206-e55511fa-e00a-4e81-bced-9714aab79618.png">
die Ladeanzeige läuft und läuft, der Ladebalken eigentlich durchgehend, auch wenn ein Updatezyklus von Bsp. 2 Minuten eingetragen ist.
<img width="1261" alt="Bildschirmfoto 2022-10-08 um 07 10 37" src="https://user-images.githubusercontent.com/15359915/194690203-d33a04c2-7cf4-476a-a54d-d7bdfd304854.png">

**Comment by Starter4711** [comment]
es scheint es gibt einen Zusammenhang mit der Influxdb, die geht im Docker auf Power und Ramverbrauch bei Zugriff.

**Comment by Apollon77** [comment]
Naja ... es werden in dem Fall 4 queries parallel ausgeführt gegen die InfluxDB ... enn Sie die Daten nicht im RAM hat kommt es zu I/O ... Ohne mehr details was da wie genau abgefragt wird schwierig zu sagen aber dann wird die influxdb ihre zeit brauchen um die Daten zu liefern ...

**Comment by GermanBluefox** [comment]
Wenn schon, dass ist das nicht ECharts problem, but influx
