### ISSUE TITLE
Update auf 0.4.8 nicht möglich

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.echarts#19]
Er arbeitet ganz Lange nach dem Druck auf den UpdateButton, dann schließt er das Fenster und es ist noch immer die 0.4.7 installiert.

**Comment by sigi2345** [comment]
Dito

**Comment by DocGame69** [comment]
Hier genau das selbe....

**Comment by apla2016** [comment]
Same here, not able to update from 0.4.7 to 0.4.8. It goes through update process, but stays at 0.4.7

**Comment by GermanBluefox** [comment]
Will be fixed with 0.4.9

**Comment by Baenker** [comment]
Kann geschlossen werden. Konnte die 0.49 installieren
