### ISSUE TITLE
Legendeneinträge untereinander 

### ISSUE THREAD

**Issue by baennjer** [ioBroker/ioBroker.echarts#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

In Flot ist es möglich die Legende flexibel darzustellen. 
Durch Angabe der Anzahl der Spalten (z.B. 1) in der Legende ist es möglich die Legendeneinträge untereinander anzuordnen.
Zur Zeit wird die Legende als Fließtext dargestellt und kollidiert mit dem Diagrammtitel wenn dieser oben, mittig platziert ist.
Findet ihr dass das eine gute Idee ist oder bin ich der einzigste?

**Comment by GermanBluefox** [comment]
Flot und echarts sind komplett unterschiedlich und es gibt einiges, was echart doch nicht kann.
Allerdings, Vertikale legende ist in 0.4.9 implementiert.
![image](https://user-images.githubusercontent.com/4582016/102802021-55f28c80-43b6-11eb-8c78-789c2d8ee319.png)

**Comment by baennjer** [comment]
danke - ich bin begeistert von diesem Adapter
