### ISSUE TITLE
Hover Info nur für eine Kurve und nicht mit allen Werten

### ISSUE THREAD

**Issue by baennjer** [ioBroker/ioBroker.echarts#23]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Ist es geplant die Hover Info analog zu flot anzupassen?
Ich persönlich finde die gleichzeitige Anzeige mit den Werten aller Kurven zu unübersichtlich. 
![image](https://user-images.githubusercontent.com/32200998/102688224-8b9c4780-41f5-11eb-9b71-39692632d588.png)
In flot ist das meiner Meinung nach viel übersichtlicher da man genau den Wert erhält den man mit dem Mauszeiger gerade hovered:
![image](https://user-images.githubusercontent.com/32200998/102688298-33b21080-41f6-11eb-9455-83a1ef737c3b.png)

Vielleicht sehen das ja noch mehr Nutzer so wie ich. 
Auf jeden Fall ist eCharts ein super Projekt und zu 100% in den ioBroker integriert was die Bedienung betrifft. Ich habe schon komplett umgestellt.

**Comment by GermanBluefox** [comment]
Ab 0.4.9
![image](https://user-images.githubusercontent.com/4582016/102803070-f5644f00-43b7-11eb-8495-ac9ea86b5118.png)

**Comment by baennjer** [comment]
danke!!
