### ISSUE TITLE
How to display only a true/false value?

### ISSUE THREAD

**Issue by ltspicer** [ioBroker/ioBroker.echarts#232]
Is it possible to display only a true/false value as a line?

**Comment by ltspicer** [comment]
It works!
![Auswahl_002](https://user-images.githubusercontent.com/11616336/208217378-70929c2d-e8df-4d25-a76b-246e5fb420ac.png)

**Comment by derrapf** [comment]
The x-Axis is a time axis. Your device sets the true value probably is set for a certain amount of time. So this is what the chart will show when you display a boolean value. 
What you showed above would be a true value that is immediatelly set to false again. So it's only true for some ms.
Also: In your char you never could see when the true value goes back to false.
So what is your usecase of only wanting  to see the positive (false to true) slopes of that device?
BR Ralf

**Comment by ltspicer** [comment]
Hi
Thx for answering.
It works. I want see tr-064 (present)
![Auswahl_002](https://user-images.githubusercontent.com/11616336/210663714-ce398a06-6fcf-4668-994e-d163a6bf9ab1.png)
