### ISSUE TITLE
Spalten für Legende einführen (wie in Flot)

### ISSUE THREAD

**Issue by derrapf** [ioBroker/ioBroker.echarts#233]
In Flot konnte man einstellen wieviele Spalten die Legende haben soll:
![grafik](https://user-images.githubusercontent.com/11745094/209892375-21f46d83-7bfe-4008-b132-7f3f110172ad.png)

Das ist in ECharts nicht mehr möglich.
![grafik](https://user-images.githubusercontent.com/11745094/209892331-c2505122-dab0-4cd0-8448-b86f85c32edd.png)

Bitte das dort auch einfügen.

**Comment by GermanBluefox** [comment]
You can define the height of legend what indirect controls the number of columns
![echart](https://user-images.githubusercontent.com/4582016/218471792-1016da06-eb4d-4e94-b04c-1abd21c7dd11.gif)

**Comment by derrapf** [comment]
Look different for me. I don't have those settings:
![grafik](https://user-images.githubusercontent.com/11745094/218872242-e62075bb-cd79-4a66-92a2-6b9961e49638.png)

**Comment by GermanBluefox** [comment]
So you have an old version. I have it:
![image](https://user-images.githubusercontent.com/4582016/219081700-18c89347-7294-412d-95ed-8f90e9334c4c.png)

**Comment by derrapf** [comment]
Maybe, but IOBroker dsoes not tell me that there is a newer version. I am currently uptodate with all  adapters

**Comment by GermanBluefox** [comment]
It is in 1.4.3

**Comment by derrapf** [comment]
![grafik](https://user-images.githubusercontent.com/11745094/219349222-48fd7e5a-624b-46ac-a91e-8c22d1ace526.png)

Which is not yet released, right? Because IOB does not tell me that there is a newer version available.
