### ISSUE TITLE
Nach Update auf V0.4.9 Tooltip Hintergrund nur noch Weiß

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.echarts#24]
Hallo,
nach dem Update auf die Version 0.4.9 ist der Hintergrund des Tooltips komplett weiß. Ist es möglich die Hintergrundfarbe zu ändern?

Gruß Steffen

**Comment by GermanBluefox** [comment]
Ist jetzt besser?

**Comment by Steff42** [comment]
Ja viel besser!
Danke
