### ISSUE TITLE
Show the name of a device

### ISSUE THREAD

**Issue by derrapf** [ioBroker/ioBroker.echarts#240]
On the current deice list you can not recognize the device without looking it up in "objecs" tab of IoBroker:
![grafik](https://user-images.githubusercontent.com/11745094/210551596-c46e3ed7-f780-4c2f-95ea-2d847a4de598.png)

I would appreciate, if more information is shown here. Maybe configurable table columns.

BR Ralf

**Comment by ltspicer** [comment]
You can see that under "ID".
![Auswahl_002](https://user-images.githubusercontent.com/11616336/210665220-bf347840-2712-48f3-88a7-1b61ee5f5966.png)

**Comment by derrapf** [comment]
No
Not for the Shellys for example
![grafik](https://user-images.githubusercontent.com/11745094/210674985-1a7c4617-d296-4fa5-a4e4-8d09b7d21dbc.png)
I would need the name, since the ID of some devices are cryptical:
![grafik](https://user-images.githubusercontent.com/11745094/210675103-11f351c2-e5e5-4c5d-8a35-881b9b918df1.png)
BR Ralf
