### ISSUE TITLE
Rounding error for y-axis

### ISSUE THREAD

**Issue by kmma-github** [ioBroker/ioBroker.echarts#241]
**Describe the bug**  
Sometimes the values for the y-axis get ugly rounded values. E.g. 19.459999999997 instead of 19.46 or better 19.5

**To Reproduce**  
It only happen sometimes, so I don't know how to reproduce

**Expected behavior**  
I expect only one digit after the comma.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![echarts_rundung](https://user-images.githubusercontent.com/68343005/212490604-ff8e82b3-b20b-4abf-bc03-243fe14caf6b.jpg)

**Versions:** 
echarts 1.0.12

**Comment by uelpenich** [comment]
Die Anzeige entspricht dem Inhalt der Historiendatenbank. Wenn Du etwas anderes haben möchtest, musst Du bei den Datenquellen die Nachkommastellen einstellten.
![grafik](https://user-images.githubusercontent.com/63613798/212548892-3117a93a-343c-4e77-a3d6-72e15a6d1dde.png)

**Comment by GermanBluefox** [comment]
Das ist die Lösung.
