### ISSUE TITLE
Keine Anzeige der Line Chart

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.echarts#249]
Hallo, 

Keine Anzeige der Line Chart nach Update auf Version 1.3.0

![Screenshot (5311)](https://user-images.githubusercontent.com/41079106/217413997-e2de6271-0ba0-41f6-aaea-14351e6df4ec.png)

Und Anzeige von NaN bei  Bar Chart

![Screenshot (5313)](https://user-images.githubusercontent.com/41079106/217414707-d0e888c0-d396-4527-9e37-53d4af933742.png)

Plattform: Windows
RAM: 16 GB 
NODE.JS: V16.19.0
NPM: 8.19.3
JS Controller: 4.0.24
Admin: 6.3.6
WS: 2.3.5
WEB: 5.4.3
Socket.io: 6.3.3
Script Engine: 6.1.4
IOT: 1.14.3
VIS: 1.4.16
VIS2. 2.0.16

**Comment by DiveSurfer** [comment]
Hi,
das kann ich bestätigen.

Node.js v16.19.0
NPM 8.19.3
Plattform linux
Betriebssystem linux
Architektur arm64
js-controller 4.0.24

**Comment by DiveSurfer** [comment]
Mit 1.3.1 gefixed, vielen Dank
