### ISSUE TITLE
Typo in Markierungen

### ISSUE THREAD

**Issue by baennjer** [ioBroker/ioBroker.echarts#25]
**Describe the bug**  
Markierungen:
Wenn  die Bearbeitung eingeklappt ist steht 2 mal "Oberes Wert oder  ID"
![image](https://user-images.githubusercontent.com/32200998/102913237-c6fd7700-447e-11eb-957c-b579b5abc1c4.png)

Wenn ausgeklappt dann stimmt es bis auf die Formulierung, sollte besser Oberer und Unterer heißen:
![image](https://user-images.githubusercontent.com/32200998/102913292-dbda0a80-447e-11eb-9292-66427c94c150.png)

**Versions:**  
 - Adapter version:  0.4.9
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Comment by GermanBluefox** [comment]
Will be fixed in next version
