### ISSUE TITLE
Legendenhintergrund doppelt

### ISSUE THREAD

**Issue by Bernd9000** [ioBroker/ioBroker.echarts#253]
v1.4.0 und vorher
Legendenhintergrund ist zweimal in `Optionen` vorhanden ?

![Unbenannt](https://user-images.githubusercontent.com/77005685/218694941-c447364e-d1a2-4f08-8137-bb3665cd3b90.jpg)

**Comment by GermanBluefox** [comment]
Danke. Fixed

**Comment by Bernd9000** [comment]
Ist bei mir noch vorhanden.
Stelle gerade fest das die `PresetTabs.js` gar nicht im IOBroker Verzeichniß vorhanden ist.
Merkwürdig.......
Da läüft irgendwas mit der Installation nicht richtig
