### ISSUE TITLE
im Preset ausgewählte instanzen lassen sich nicht bearbeite

### ISSUE THREAD

**Issue by Biker58** [ioBroker/ioBroker.echarts#254]
Wenn ich die im Preset enthaltenen Instanzen bearbeiten will, erschein nur ein leerer Bildschirm

**Comment by GermanBluefox** [comment]
Da muss in der Browser-Console eine Fehler-Meldung sein.

**Comment by Biker58** [comment]
TypeError: (intermediate value).palette[i.color] is undefined
    H Button.js:100
    u createStyled.js:179
    d emotion-serialize.browser.esm.js:139
    f emotion-serialize.browser.esm.js:253
    V emotion-styled-base.browser.esm.js:123
    i emotion-element-6a883da9.browser.esm.js:36
    React 14
    onClick Line.js:405
    React 16
    e index.js:25
    <anonymous> index.js:40
    <anonymous> serviceWorker.js:129
    <anonymous> serviceWorker.js:129
instrument.ts:124
    dt instrument.ts:124
    React 15
    onClick Line.js:405
    React 16
    e index.js:25
    <anonym> index.js:40
    <anonym> serviceWorker.js:129
    <anonym> serviceWorker.js:129

**Comment by GermanBluefox** [comment]
Welche echarts version?

**Comment by Biker58** [comment]
Version 1.2.1 war noch ok. Fehler tritt bei 1.3.3, 1.3.4, 1.4.0 und 1.4.1 auf

**Comment by GermanBluefox** [comment]
Und was ist mit 1.4.3 von npm (nicht github)?

**Comment by Biker58** [comment]
Es geht, wenn ich bei den Instanzen auf den Ordner klicke, bei dem Bleistiftsymbol verschwindet der Inhalt.
Mit dem Ordnersymbol hatte ich vorher nicht getestet. Sorry

**Comment by GermanBluefox** [comment]
> bei dem Bleistiftsymbol verschwindet der Inhalt.

Kann reproduzieren. Danke
