### ISSUE TITLE
V 1.4.1 Keine Anzeige der Charts

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.echarts#255]
Hallo,

nach einen Update auf V 1.4.1 werde keine Charts mehr angezeigt.
Mit V 1.4.0 funktionierte noch alles.

![Screenshot (5349)](https://user-images.githubusercontent.com/41079106/218769370-bd8426a5-52ae-4214-83c4-c9fcc5bf5352.png)

Plattform: Windows
RAM: 16 GB 
NODE.JS: V18.14.0
NPM: 9.3.1
JS Controller: 4.0.24
Admin: 6.3.6
WS: 2.3.5
WEB: 5.4.3
Socket.io: 6.3.3
Script Engine: 6.1.4
IOT: 1.14.3
VIS: 1.4.16
VIS2. 2.0.16

**Comment by Bernd9000** [comment]
Bei mir hängt es mit dem Fill Wert zusammen wenn dieser > 0 ist.
![Unbenannt](https://user-images.githubusercontent.com/77005685/218795057-c6418a33-e96d-4048-a38f-ab161c33d359.jpg)

**Comment by Baenker** [comment]
habe das gleiche Problem. Ich kann kein Muster erkennen.

**Comment by beandi** [comment]
Ich benutze auch fill, bekomme folgenden Fehler im Log (bei einem bestimmten Chart mit vielen Daten):
`
echarts.0 | 2023-02-15 14:03:20.925 | error | LinearGradient is not a constructor
echarts.0 | 2023-02-15 14:03:20.925 | error | TypeError:  LinearGradient is not a constructor    at  /opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartOption.js:496:34     at Array.map (<anonymous>)    at ChartOption.getSeries  (/opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartOption.js:390:30)     at ChartOption.getOption  (/opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartOption.js:1076:29)     at ChartModel.onUpdateFunc  (/opt/iobroker/node_modules/iobroker.echarts/main.js:135:40)    at  /opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:1402:30     at ChartModel.readMarkings  (/opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:1209:20)     at Timeout._onTimeout  (/opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:1264:39)     at listOnTimeout (node:internal/timers:559:17)    at processTimers  (node:internal/timers:502:7)
echarts.0 | 2023-02-15 14:03:20.918 | error | uncaught exception: LinearGradient is not a constructor`

**Comment by Grothesk242** [comment]
Mit aktuellem web-Adapter funktioniert es bei mir wieder.

**Comment by sigi2345** [comment]
Läuft wieder mit 1.4.2

**Comment by Baenker** [comment]
bei mir auch. Sollte dann ggf geschlossen werden
