### ISSUE TITLE
rendering TRUE/FALSE as 1/0 breaks echarts 

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.echarts#256]
With a true/false value the displayed echarts image renders between correct and broken

1: chart width some values like temperatures and a true/false value like coming from a windows open/close sensor
2: window closed: broken rendering (No values, legend all in one line upper left)
3: open window: imediately the echart image becomes ok!, all Values inkl true/false are display correctly, legend is ok

looking at the browser seeing the broken chart, only! open the window and the chart becomes immedeately ok!

see attached pictures

Expected behavior
to see a line represententing true/false as interpreted as 1/0 displayed as line, going from 0/false to 1/true

Versions  
 - Adapter version: 1.4.4 NPM installed
 - JS-Controller version: 4.0.24 admin 6.3.6
 - Node version: v16.19.0 
 - Operating system: win10/firefox with clearing of cache
 - Info: the true/false value is scaled "min 0" "max 19" "null as default"

![Image 003](https://user-images.githubusercontent.com/10156426/219349352-f4a32e7f-e6c1-4627-8128-a0b848ee9cbc.png)
![Image 001](https://user-images.githubusercontent.com/10156426/219349358-6f071379-3870-4c42-9c08-cea0360d4c4f.png)

**Comment by harvey637** [comment]
same error also with chrome

**Comment by harvey637** [comment]
looks like ALL true/false values break the echarts by now, tested with other charts that contain native booleans.

Even if the window (above pictures) is open/TRUE there is no line of the windows value. 
To reproduce:
- deselect everything but the wondows_open
- toggle this boolean value in legend: nothing happens

Expected:
to see a line representing the open(TRUE) and closed(FLASE) window

additional:
when showing the units (y axe position=left) the words FALSE (on the 0 position) and TRUE (on the y ticks 1,2,3,4 ....) are displayed

**Comment by harvey637** [comment]
and some more info:

it directly depends on  "OPTIONS" - "SHOW VALUES"

If set: problem with boolean
if unset: no problem

**Comment by GermanBluefox** [comment]
> when showing the units (y axe position=left) the words FALSE (on the 0 position) and TRUE (on the y ticks 1,2,3,4 ....) are displayed

See here: https://github.com/ioBroker/ioBroker.echarts/issues/257

**Comment by harvey637** [comment]
confirmed!
