### ISSUE TITLE
TRUE (on the y ticks 1,2,3,4 ....) are displayed

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.echarts#257]
when showing the units (y axe position=left) the words FALSE (on the 0 position) and  TRUE (on the y ticks 1,2,3,4 ....) are displayed.

Only FALSE and TRUE once should be shown.

**Comment by harvey637** [comment]
Hi @ Bluefox
yeeees, but :-)

I have some booleans that are displayed with small hight, like to show the state of a window, where my main interest is in temperatures and so on.
So I scale the boolean from e.g. 0 to 20 so the line (or area with filled color and line_size=0) only covers a smal part of the chart.

Then it might be an demanding task where to display only ONE y-axis-tick with the work "true". For me this is not so important as booleans as I use them are never with units on the y-axis.

But displaying only one "true" on the hight of the "scaled to max" y-tick is perfect.

Thank You!
cu
Harvey

**Comment by harvey637** [comment]
Still remember my question/enhancment to "rename" booleans to something better fitting, like "true/false" -> "open/closed" or
"true/false" -> "running/stopped"

just if you are on that corner ....
Thank You
cu
Harvey

**Comment by GermanBluefox** [comment]
> Still remember my question/enhancment #90 to "rename" booleans to something better fitting, like "true/false" -> "open/closed" or "true/false" -> "running/stopped"
> 
> just if you are on that corner .... Thank You cu Harvey

Like this?
![image](https://user-images.githubusercontent.com/4582016/219447534-d9df7629-c07c-4484-8ddf-e81e2bea6691.png)

**Comment by Bernd9000** [comment]
Wäre es möglich den `Text bei wahr` und `Text bei falsch` auch in der Legende als Wert anzeigen zu lassen ?
Bei mir ist die Klammer in der Legende leer.

**Comment by harvey637** [comment]
seems to me that "true" and its replacement is "stable" displayed, while "false" AND the replacement IS thersometimes, but vanishes ....
cu
Harvey

**Comment by harvey637** [comment]
Hi,
from my idea a boolean is always true or false and not null :-)
Inside the influxdb I only have values of true and false .... never anything else.

But I have the idea that you read the states from the device directly???  This came into my mind with the closed problem, when opening of a windows IMMEDEATELY changed the chart to ok. With influxdb the value is written into db only with a short delay.
But this was immedeately, not with a delay.
I changed too much in the echarts-definition, but I am shure that it was always "from influxdb.0" instance ...

**Comment by harvey637** [comment]
I confirm that I have:
closing a windows gives "[geschlossen]" immedeately
reloading the browser window now shows only empty brakets :-(
data comes from "influxdb.0" not "default"
datapoint inside the database is "false"

If you give me some direction how to see the value inside the program I can try to test, opening, closing windows, reloading firefox seems easy ...

cu
Harvey

**Comment by harvey637** [comment]
repeatable!

**Comment by harvey637** [comment]
when I click on the 3 1/2 lines button right of the datapoint-ID the value shown is correctly "false"

![grafik](https://user-images.githubusercontent.com/10156426/219606342-61d3a460-6d3e-414f-aef0-e761e51cf406.png)

but the legend shows only brakets ....

**Comment by uelpenich** [comment]
> seems to me that "true" and its replacement is "stable" displayed, while "false" AND the replacement IS there sometimes, but vanishes after some time by mistery.... cu Harvey

The same for me (I use Mariadb database):
- "true" and its replacement is "stable" displayed
-  "false" AND the replacement is displayed only one time, it disappears with the first refresh of the chart

**Comment by GermanBluefox** [comment]
Fixed in 1.4.7 (wait for it)

**Comment by uelpenich** [comment]
Bingo. Funktioniert wie vorgesehen. 
Danke für die Nachtschicht.

**Comment by harvey637** [comment]
Hi, working!

small issue: when sizing a boolean, so that the resulting line is relativly small hight the "upper" text is not displayed at the y-axis, although there is plenty of room.

Not really important as y-axis is never used (by me) with booleans, I am happy with the (replacment) text in the hover.

to be closed - Big Thank You to Bluefox

**Comment by GermanBluefox** [comment]
> Hi, working!
> 
> small issue: when sizing a boolean, so that the resulting line is relativly small hight the "upper" text is not displayed at the y-axis, although there is plenty of room.
> 
> Not really important as y-axis is never used (by me) with booleans, I am happy with the (replacment) text in the hover.
> 
> to be closed - Big Thank You to Bluefox

Screenshot?

**Comment by harvey637** [comment]
this is with min/max 0-7, text is replaced correct:
![grafik](https://user-images.githubusercontent.com/10156426/220873603-90e3d65d-d146-4acf-8c06-9c01d3e67995.png)
with min/max 0/1 the text is in the upper left corner

![grafik](https://user-images.githubusercontent.com/10156426/220874378-39c62a21-fef1-4cce-8f33-797ae2fd4049.png)

with min/max 0/7.4 the true-text is displayed (about 8 times textsize above the false-text), with min/max 0/7.5 it is gone.

**Comment by harvey637** [comment]
![grafik](https://user-images.githubusercontent.com/10156426/220876494-f7823eef-6aae-4271-858c-25f3b5adace6.png)

also with multiple texts, felft is ok with max=7.4, right is missing some texts with max=7.5

![grafik](https://user-images.githubusercontent.com/10156426/220876807-a6a719c5-f389-4fc7-bbfd-be8cbca2b9c9.png)

**Comment by harvey637** [comment]
after some testing I found that it has to do with the ticks of the y-axis.
I manually set the tick to 14 I get all texts correctly.
![grafik](https://user-images.githubusercontent.com/10156426/220881438-27084cf0-9aaf-4bc7-a896-9baf0f39bdfb.png)

So it looks like an 7.5 ticks implicitly if no input in this field
![grafik](https://user-images.githubusercontent.com/10156426/220881736-b9c7103d-305e-4dcd-aec6-4945695c12d4.png)

So this is not really a BUG, but strange. The y-ticks are from the first datasource line I assume, so edited ticks from later lines are not visible .... only with this strange side effect.
![grafik](https://user-images.githubusercontent.com/10156426/220882547-bd3946e5-4c51-46d5-8600-92165e742559.png)

With a different firrst line the background grid of the chart is take from this line (temperature with no extra input on y-axis ticks).
with manual large number of ticks for the now second line with the enumerations the text is also displayed.

So it is NO BUG IMHO, but some learning about y-axis ticks that are not displyed, but used for the text on the axis.

I learned a lesson, can be closed! Maybe a notice in the documentation ....

**Comment by harvey637** [comment]
![grafik](https://user-images.githubusercontent.com/10156426/220885086-2c816f8f-37f7-4807-bb8a-35864dd3dbe0.png)

My test even work with min/max = 0/60  with y-tixks of 42! text is still ok!

**Comment by uelpenich** [comment]
The width of the y-axis is not dynamic for boolean or enum data sources, but for numeric sources (?).
Is a dynamic y-axix width easy to realize with the echart package? It is just a "nice ho have". 
May I remember my proposal for an enhancement "multiple y-axis issue #42"? It is useful for diagrams with datasources with more than three different units or scales. Thank you.

**Comment by harvey637** [comment]
HI @ uelpenich
remember there is no "enum" datasource, only boolean and number. 

booleans can have units (in the homematic definition), but that makes no sense to me (I did not find any example yet)
booleans are false/true, but boolean variables from homematic can have different (status-)text for "true" "false" (eg. "raining", "no rain")
booleans look like a fixed scale of 7.5 ticks IF not manually overridden (y-axis ticks)

numbers can have units, some dont (eg. UV-Index)
numbers can have status texts, which is declared in the datapoint source. "enum" variables from the homematic are this kind of number, also this implicates integer (the index to the position) and status-texts (eg. "0:off";"1:heating";"3:cooling";"4:defrost")
numbers can autoscale

so sadly there are no real "enums" in echart datapoint :-(

I often have different y-axis, eg temperature and humidity. Than I manually set the min/max of the first datasource to something so I get defined y-axis ticks eg 6 Ticks with temperature from 10°C- 35°C (right unit) and humidity from 0% - 100% (left unit).
Which magically shows units of 0%, 20%, 40%, 60%, 80%, 100% onthe left on the y-gridlines for 10°C, 15°C, 20°C, 25°C, 30°C, 35°C.
I am quite happy with this, altough sometimes it is not so easy to find good min/max an count of ticks.

Many y-axis and many y-grindlines might look ok with 2~3 but tend to look confusing with more IMHO.

So if this a "nice to have " for you may be that my used of coincidently resusing the y-gridlines with left/right units might be easy to use and do not need any programming.
just my idea :-)
cu
Harvey

**Comment by uelpenich** [comment]
HI @ Harvey, 
thank you for your detailed answer and explanations. 

>> . . .  (in the homematic definition) . . .
for me it looks like that iobroker is build around homematic features. While I don't use homematic but knx, OWFS and vcontrol adapters, I have some difficulties to understand this thread. 

Since the vcontrol adapter also delivers some enum information (like Betriebsart, . . .) I would be glad to show them in charts. Unfortunetly the vcontrold together with the viessmann adapter convert the enum information to text strings, and text strings can't be displayed in echarts. I can configure vcontrold to deliver the information as number as it is the original information delivered by the Viessmann heater interface, but the number is not accompanied by state information as it seems to be in some homematic devices. (you described the same problem with some HomematicIP devices (Wandthermostat). 
>> so sadly there are no real "enums" in echart datapoints :-(
Do you see any way to add the state definition to the object description of the data point? I would prefer to use the linked devices adapter to keep the additional state info. 

>> . . . I often have different y-axis, . . .
I do it the same way, but this means I have to remember in my mind some scaling info. That means others than me are not able to understand the chart. 
>> . . . altough sometimes it is not so easy to find good min/max and count of ticks. . . 
I know some cases and therefor my request is more than "nice to have". 
>> Few y-axis and few y-grindlines might look ok with 2~3 but tend to look confusing with more IMHO.
You are right. 

Thanks
Uelpenich

**Comment by harvey637** [comment]
Hi,
I guess you are noch active in homematic forums, becaus iobroker issues is not the right place.

Some information on how the information is fetched from homematic objects can be found inside examples and please read the objects from iobroker.echarts. 

Minimal entry can be:
- isboolean: true
- truetext
- falsetext
- status { ..... }
and you can try to edit your non homematic stuf possibly there. Or in the object, that is fed into the history database of your choice. Lines with isnumber....manval, maxval, status ... 0:OFF, 1:ON .... just try. save often and try again.

Just edit thing, save, check the saved objects. Maybe you can find a lot of information. But remember, this is NOT what echarts was made for, so a lot of things can change without any notice, this is no officail api to do so!!!!!

good luck
Harvey

**Comment by uelpenich** [comment]
Thank you for your hints, I got it working by adding **common.states** definitions to a data source object.
