### ISSUE TITLE
booleans look gret now, what about enums?

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.echarts#258]
Hi @Bluefox 
your solution with booleans and the replacement text looks really great, Thank You! (although sometimes I have only brakets, no true/false and not the textual substitution .... still checking for the reason. Open and close gives value immedeately back ...) 

Sadly some device states are with two states, but transported as enums. Example (of a Wall-temperaturcontroller):

```
{
  "type": "state",
  "common": {
    "name": "Wandregler-AZ:1.WINDOW_STATE",
    "def": 0,
    "type": "number",
    "read": true,
    "write": true,
    "min": 0,
    "max": 1,
    "states": {
      "0": "CLOSED",
      "1": "OPEN"
    },
    "role": "value.window",
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "storageType": "",
```
while the sending connected device, a windows/door sensor, gives true/false with the window, the reflected state in the connected wall-temperature-controller is enum :-(

But wait, the "names" of the values 0/1 are part of the definition of the device. Can you read them from the definition and use them in the chart, e.g. very similar to the true/false text substituation?
min, max, states ["...","..."] are all there. This also is correct with enums >=2, but maybe more demanding with the space on the screen.
Also these txt-boxes could be prefilled with the definition from the device-configuration, but open to modification.

Here some definition example with more enums:
```
{
  "_id": "ems-esp.0.boiler.hpactivity",
  "type": "state",
  "common": {
    "id": "boiler.hpactivity",
    "name": "ems: compressor activity",
    "type": "mixed",
    "read": true,
    "write": false,
    "role": "value",
    "states": {
      "0": "none",
      "1": "heating",
      "2": "cooling",
      "3": "hot water",
      "4": "pool",
      "5": "unknown",
      "6": "defrost"
    },
    "custom": {
      "influxdb.0": {
```

Just my input to enhancing the echarts, nothing important or waiting for ..... keep your time, and thank you for looking inti this.
If you want more examples simply ask for more :-)

cu
Harvey

**Comment by harvey637** [comment]
![Image 004](https://user-images.githubusercontent.com/10156426/219594360-4c101e14-e9fc-45c6-b42d-541530cfe7ea.png)

Here you can see the booleans of the window perfectly replaced ("offen/gekippt" - "geschlossen")
Some other datapoints are enums:
SET_POINT_MODE is sadly a number min=0, max=3 without states text ...... ("Manuell wegen Urlaub") - nothing to do :-(
WINDOWS_STATE has "OPEN" and "CLOSED" as status, much better ("Absenkung wegen Fenster"):-)

just for info: the openning of the real window has some time before the state of the temperature-controller is changed, also on the closing of the window. I want to very short open/close window without reaction from the heating system, after closing of the window it takes some time for the room to heat up from walls and floor (if it is very cold outside) so I reset the temperature to normal only after some additional time. This is the reason I have both the window.state and the controller.windows_state ... 

![Image 005](https://user-images.githubusercontent.com/10156426/219597570-d4ddded1-0058-4e22-b47a-5a71135e8308.png)

**Comment by GermanBluefox** [comment]
> although sometimes I have only brakets, no true/false and not the textual substitution

May be because it is null....

**Comment by GermanBluefox** [comment]
> Sadly some device states are with two states, but transported as enums.

I knew, It will never end :)

**Comment by harvey637** [comment]
I hope it is the fun part that will never end!

**Comment by harvey637** [comment]
oh, its me again :-)

... still this "false" problem, mybe near the autorefresh ?!?

some other collateral damage:
in the hover popup is a strange mixture of correct replacement string (true-> "offen/gekippt") / (false->"geschlossen") followed by some strange word ("offen").
The bold stringpart seems to come from the boolean replacement strings, but a non bold stringpart after that shows only the word "offen", which comes from ???? maybe from the status of the sensor itself?

![grafik](https://user-images.githubusercontent.com/10156426/220070033-928e901e-48a5-452a-b5d8-3ddd17d2ee06.png)

hope this helps.
If you want me to test some special variant of the echarts (with displaying the source of the missing fals in the brakets after autorefresh), just say so and give me some instructions how to use. opening/closing window is easy to do! thank you
cu
Harvey

**Comment by harvey637** [comment]
Hi,
forget about my last post please! my mistake :-(

Reason was:
BEFORE the booleans replacment text I had units like "offen" to make the display nice.
With 1.4.6 the GUI does not show this unit option anymore, so I cannot delete it, but I found it in the echarts-object of this graph.
Edited to "" - now the THIS problem is gone.
I remember some small problem there, when a datasource object contains a unit that does not make sense. editing it to "" in the GUI did not work. So I used some innocent text there.

**Comment by GermanBluefox** [comment]
Implemented: 
![image](https://user-images.githubusercontent.com/4582016/220477318-78789194-e89a-45d5-9e3e-bf9ed0c63cf9.png)

![image](https://user-images.githubusercontent.com/4582016/220477335-b5b1860a-7b8b-40b1-98f5-7e74321e7d0a.png)

**Comment by harvey637** [comment]
Thank You @Bluefox!

Very nice and excellent solution!!!

Now I have to edit a lot of charts but I love it!

But as always there is something not yet found:
I have some multisensor that can use different sensors like humidity, temperature, light, uv, barometric pressure and so on. These sensors have a valid range e.g. -99,9 - 120 °C, but also a NO_SENSOR status. So the same sensor_hardware and firmware can have different sets of sensors like only with temperature, but no barometric pressure. The sensor_hardware than sends the info to ccu/iobroker with a value of NO_SENSOR status. Creating a graph makes no sense for a sensor that is not attached. So with real NO_SENSORS this is never a problem ass this datasource is not recorded and not displayed, but here you can see the outcome with a real attached sensor.
Due to this perfect scheme with booleans, enums and the evaluation of the status this becomes a problem for numbers. I attached the configuration of such a device and the chart. 

Maybe evaluate "states" only with "boolean" and "enum"? 

cu
Harvey
![grafik](https://user-images.githubusercontent.com/10156426/220557584-6cb9c49c-edeb-45a1-927c-4f905245957c.png)

**Comment by harvey637** [comment]
to add some information:
the VALUE is shown correctly in the graph, eg. 19.8 "C from a temperature sensor, a line going up and down during the day.
"Only" the unit is "gone" in the echarts GUI and the legend, also no value of the cursor position, (possible y-asix) of the chart and replaced by the status text. Auto calculation min/max might be affected also.

for more information please ask!
cu
Harvey

**Comment by harvey637** [comment]
another extreme example:
all sensorselements are active, but on an other device with the same firmware might be absent, so the possible status "NO_SENSOR" with a (never met) value is part of the device configuration. (identically to the example above)  

![grafik](https://user-images.githubusercontent.com/10156426/220594621-28be4eac-5e9d-462e-b594-2d98e310cabc.png)

**Comment by GermanBluefox** [comment]
What about if you can disable the usage of states?
![image](https://user-images.githubusercontent.com/4582016/220597762-5a83fd68-b788-4bcf-a0fe-301cf920d8fb.png)

But it must be done...

**Comment by harvey637** [comment]
yes, looks like a good idea.
so if "dont use status names" the value and unit in the hover come back and the units are editable in the GUI)
"use statusnames" never have units (hopefully:-) and the value is the status text.

Lets think about, that status names IS ONLY used and sensible for booleans and enums, never for numbers?
So ignore any status in the configuration for non booleans and non enums? 
Numbers always have a value (that might be outside min/max eg. if an error in a single measuement) and I guess that they always have some kind of units( until found/proved wrong :-)

With booleans/enums if I have a unit I can write it in the text eg. "closed/oppend 50%/open"

So - hmmmm - no units with booleans/enums, and units with numbers. No need to switch number of options with the result of a switch.
cu
Harvey

**Comment by GermanBluefox** [comment]
there is no common.type = 'enum'. Only: array, boolean, file, json, mixed, multistate, number, object and string.

But units could solve the problem. Number with unit does not have states

**Comment by harvey637** [comment]
sorry, I checked some devices an see that some have a number and valid status.

the datatyp "enum" seems not to exist and is "number" with (or without) status names.

So for get my second idea, we need your toggle switch and units (that might be empty).

**Comment by harvey637** [comment]
I dont know if the changed (looks good to me) line.js ONLY handles lines, beacuse the topic also exists with steps. If both are handled in line.js ignore my  useless comment - thank you!

**Comment by harvey637** [comment]
lines and steps confirmed to this units or text_replacement

to be closed - Big Thank You to Bluefox!
