### ISSUE TITLE
minor problem with workaround when using y-axis from other line

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.echarts#259]
**Describe the bug**  
after adding a new datasource with default right display of y-axe units/ticks the units remain after switching to use to "y-axis from other line".

**To Reproduce**  
1. add new datasource (with units): units/ticks are now displayed on the right side y-axis by default
2. change "own y-axis" to "use y-axis from line" (eg. two humidities with 0-100%): the options for individual y-axis are hidden inkl. default "y-axe position: right)
4. See error: units are still displayed at the default right y-axis

**Expected behavior**  
the new datapoint should completly use ALL options for y-axis of the referred line inkl hiding of y-axis or left display of y-axis 

**Versions:**  
 - Adapter version: 1.4.6

WORKAROUND:
Select "none" display of y-axis BEFORE using "use y-axis from line xxx"
If the referred line has displayed units/ticks on any side of the chart we dont need the display of SAME units again, they are already shown from the referred line and min/max are correct.
If the referred line has no units/ticks displayed than displaying nothing is correct too.

This leads to my idea, that the "y-axe position" is ALWAYS "none" with a repeated y-axis.
"min", "max", "y-axe ticks" are REPEATED from the referred line

cu
Harvey

PS bye the way: moving the order of lines has funny sideeffects an referring to moved lines, minor-minor-minor problem :-)))
PSS something minor-minor is wrong with CSS: selected tab (datasources/marks/time...) have NO color and are unlegible.

**Comment by GermanBluefox** [comment]
Now the units will be taken from common Y axis.
