### ISSUE TITLE
Line thickness flickering while moving the mouse

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.echarts#26]
**Describe the bug**  

**To Reproduce**  
See attached video
https://user-images.githubusercontent.com/17641229/102982010-23f23f00-450a-11eb-9909-8d98263196e5.mp4

**Expected behavior**  
No flickering

**Versions:**  
 - Adapter version: 0.4.9
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Comment by baennjer** [comment]
I suppose that is a highlighting function to indicate which line is pointed to with the mouse pointer.

**Comment by AlCalzone** [comment]
Except that I don't highlight any lines as you can see in the video

**Comment by baennjer** [comment]
As soon as the vertical indicator hovers a datapoint on any line it changes to bold and shows it's value in the tool tip. I might be wrong but that would explain it....

**Comment by AlCalzone** [comment]
Ok that would explain it, but hovering the lines looks stupid. The previous versions didn't do that and still showed the tool tip.

**Comment by baennjer** [comment]
Yes, I agree.
Infect I was even more satisfied with hovering in FLOT where you could track just one line and got only it's values instead of getting displayed the value of any datapoints you just accross all lines.

**Comment by GermanBluefox** [comment]
Should gone now.

**Comment by AlCalzone** [comment]
👍🏻
