### ISSUE TITLE
inconsistency with new boolean replacment text and suplied text from status of datasource

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.echarts#260]
Hi @ bluefox
with 1.4.9 I have some irritation:

existing homematic variable type boolean with native text:
![grafik](https://user-images.githubusercontent.com/10156426/220867237-af673090-6697-4b16-bf5d-4381941865d0.png)

definitvly NO sunshine today and the last > 2 month , as the variable is true with a lot of sun and temperature above 20!C

history in influxdb, also false (now):
![grafik](https://user-images.githubusercontent.com/10156426/220867811-5e59eced-ca01-4008-9d21-62a3859df5dd.png)

used in chart (deleted and freshly added):
![grafik](https://user-images.githubusercontent.com/10156426/220868161-2b0fd631-951c-475e-b1ec-c6055e079f53.png)

with "use state names" ON display shows WRONG "Sonnenschein":
![grafik](https://user-images.githubusercontent.com/10156426/220868420-047233d7-efd5-4303-b99f-484faf7df8e1.png)

with "state names" OFF display correct "bewölkt"
![grafik](https://user-images.githubusercontent.com/10156426/220868687-5d3c5d16-7292-4c34-8417-304607760485.png)

My question is, why do I have two places to modify the replacment text (text for false/true and inside the status replacment popup.) .... hmmmmmm. booleans have 2 fileds for false/true, why edit popup?
And sadly, why is the displayed value WRONG  when using the text from the status?

This is the part of the echarts object:
![grafik](https://user-images.githubusercontent.com/10156426/220872158-65145eb9-4d29-4d75-ab30-13288b76decf.png)

Funnily sometimes I have text replacment in the chart that is not from manual false/true text and NOT from the status name popup. Very strange that this text replacement is CORRECT for the device. Still investigating and keep you informed.

Very big thank you to this improvement, it is very helpful. minus the small glitches and my not understanding of structures.

**Comment by GermanBluefox** [comment]
How the object hm-rega.0.2957 looks like?

**Comment by harvey637** [comment]
```
{
  "_id": "hm-rega.0.2957",
  "type": "state",
  "common": {
    "name": "Sonnenschein",
    "type": "boolean",
    "read": true,
    "write": true,
    "role": "state",
    "desc": "scheint die Sonne?",
    "states": {
      "0": "kein Sonnenschein",
      "1": "Sonnenschein"
    },
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "storageType": "Boolean",
        "aliasId": "",
        "debounceTime": 0,
        "blockTime": 1000,
        "changesOnly": false,
        "changesRelogInterval": "0",
        "changesMinDelta": 0,
        "ignoreBelowNumber": "",
        "disableSkippedValueLogging": false,
        "enableDebugLogs": false,
        "debounce": 0
      }
    }
  },
  "native": {
    "Name": "Sonnenschein",
    "TypeName": "VARDP",
    "DPInfo": "scheint die Sonne?",
    "ValueMin": null,
    "ValueMax": null,
    "ValueUnit": "",
    "ValueType": 2,
    "ValueSubType": 2,
    "ValueList": "kein Sonnenschein;Sonnenschein"
  },
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1677143608908
}
```

**Comment by harvey637** [comment]
Hi @ bluefox,
I created a preset single with this rega.0.2957, still the same behaviour.
The line (or steps) are correct (although the last sunshine was 5 month ago :-)

please ask any thing more!
cu
Harvey

**Comment by GermanBluefox** [comment]
> "states": {
>       "0": "kein Sonnenschein",
>       "1": "Sonnenschein"
>     },

Please try 1.4.11

**Comment by harvey637** [comment]
Hmmmmm.... 
![grafik](https://user-images.githubusercontent.com/10156426/221381960-b3eef647-5143-4ecc-99a1-7e61590c4068.png)

now the displayed text is correct (showing "sonnenschein_false"), and it is repeated in the popup, but twice the flase text replacement ...

**Comment by harvey637** [comment]
It is ok for one time, but when I reopen the "pencil" popup both (FALSE and TRUE) are the same replacement text, after "apply" this wrong text is also copied into the chart, eg the complete chart with units (now twice the same text) and in the echarts GUI (now 0(down) and 1(up) have the same text:
![grafik](https://user-images.githubusercontent.com/10156426/221382161-0721128d-756c-427e-a927-1eeebd554aee.png)

**Comment by harvey637** [comment]
in the picture you still see the "old" 0:schattig text, in the popup the LALSE text is identical to the "TRUE" texct, both are "sonnig" and after "apply/anwenden" both text are identical, in the GUI and in the chart ...

**Comment by harvey637** [comment]
![grafik](https://user-images.githubusercontent.com/10156426/221382954-c76515e8-625a-4158-8bc1-8d96439785f4.png)

I can change the individual text are the are always changed for the correct position, very good! Thank You
cu
Harvey

**Comment by harvey637** [comment]
yes, without testing, line 58 seems to be the typo ....
Thank You, looking for 1.4.12 :-)

PS: Do you have a LIFE on sundays - go out into the sunshine ! (this is a joke about the variable "sonnenschein" causing the improvment of this boolean stuff)

**Comment by harvey637** [comment]
PPS: absolutly minor-minor-minor - just to write it down somewhere:

the word used for a datasource is (in gberman) "Linie 1 - Sonnenschein". When referring to this line in anopther datasouce y-axis the german wording is "Aus Zeile 1". Generally I would prefer "Zeile", because "line" is also used in the context of "Linie" - "Schritte". I did not invesitgate into the english handling, too lazy, especially on sundays :-)

Is it ok to write minor-minor-minor stuff into issues? It is only "beautifying", I dont want to keeo you busy with this mini things?

be the source with You
cu
Harvey

**Comment by harvey637** [comment]
Hi @ bluefox
sorry, I saw that the build process has some errors .....
testing not possible :-(
