### ISSUE TITLE
 Chart calculated values?

### ISSUE THREAD

**Issue by thomas725** [ioBroker/ioBroker.echarts#28]
**Is your feature request related to a problem? Please describe.**
I would like to plot information that I don't have explicitly stored, but can be calculated from variables I have.

**Describe the solution you'd like**
being able to specify variables like this for example:
`[fronius.0.meter.0.PowerReal_P_Phase_1]+[fronius.0.powerflow.P_PV]/3`
In VIS I am able get the described value using this syntax:
`{p:fronius.0.meter.0.PowerReal_P_Phase_1; s:fronius.0.powerflow.P_PV; ((s/3)+parseFloat(p)).toFixed(2)}`

**Describe alternatives you've considered**
A separate object with database connection could be defined and filled with the correct values somehow, but that would require additional storage (depending on the frequency and time-frame of the variable).

**Additional context**
I've previously used the flot adapter for charting which had an offset parameter which I tried to request being adapted into an generic modificator here: https://github.com/ioBroker/ioBroker.flot/issues/87
But as @Apollon77 informed me this is the charting adapter that is now under active development so I thought I'll try my luck here.

**Comment by GermanBluefox** [comment]
I could, relative easy, implement the convert for one time series, but for 2 timeseries there is a problem.
The datapoints are not always written on the same time, so second TS must be interpolated to have values by times on first TS.

**Comment by thomas725** [comment]
Sorry for the long reply-time. We could interpolate values like you do in the mouse-over popup, or if that is too complex instead use the values with the smallest time-delta to the timestamp of the first variable.

Have been talking about the same feature request here:
https://github.com/ioBroker/ioBroker.flot/issues/101

**Comment by GermanBluefox** [comment]
>We could interpolate values like you do in the mouse-over popup
it is not so easy. I will be glad about PR for this request.
