### ISSUE TITLE
Disable Auto dark mode

### ISSUE THREAD

**Issue by DasLukas** [ioBroker/ioBroker.echarts#30]
It seems that the charts have a auto dark mode. Is it possible to deactivate it so the background always be white?

**Comment by GermanBluefox** [comment]
It is prepared for admin5 that could control the theme. Just now you can set the theme in javascript adapter.
![image](https://user-images.githubusercontent.com/4582016/106934609-99ad1580-671a-11eb-9187-c4762a0b190e.png)

**Comment by DasLukas** [comment]
Change the theme in script. Same problem. 

![image](https://user-images.githubusercontent.com/56454319/106944912-78065b00-6727-11eb-9255-66807bac9da2.jpeg)
