### ISSUE TITLE
embedding chart in iFrame

### ISSUE THREAD

**Issue by stephan1827** [ioBroker/ioBroker.echarts#32]
Hi,
I created a chart and try to embed it into Jarvis via iframe. When I download the page Firefox and other browsers refuse to load the chart. See on the top right. Charts from the iobroker vis load fine. Is there anything I have to change to make this work?

<img width="1584" alt="Bildschirmfoto 2021-03-06 um 10 44 16" src="https://user-images.githubusercontent.com/2972703/110202469-2b6a8880-7e69-11eb-8e5a-6c19c00115a6.png">

**Comment by GermanBluefox** [comment]
I cannot reproduce it:
![image](https://user-images.githubusercontent.com/4582016/110952307-5ad83400-8346-11eb-8438-34f2c02737ba.png)
On which IP runs jarvis and on which echarts?

**Comment by stephan1827** [comment]
This is my jarvis address
http://192.168.86.90:8082/jarvis/index.html#instance=0

This is the graph that works
http://192.168.86.90:8082/vis/index.html?jarvis#SolarGraph1

This is echarts
http://192.168.86.90:8081/adapter/echarts/chart/index.html?preset=echarts.0.Solar

Could it be that the different port creates an issue? The echart works fine if I just open it in a browser

**Comment by GermanBluefox** [comment]
Try to use
http://192.168.86.90:8082/echarts/index.html?preset=echarts.0.Solar

**Comment by Berchemer** [comment]
> Try to use http://192.168.86.90:8082/echarts/index.html?preset=echarts.0.Solar

Thanks for this example-URL.

I also had problems here inside an iFrame with the URL:
http://192.168.165.139:8081/adapter/echarts/chart/index.html?preset=echarts.0.WetterstationTemperaturAktuell

Changing this to:
http://192.168.165.139:8082/echarts/index.html?preset=echarts.0.WetterstationTemperaturAktuell

solved my problem.

Maybe a button inside the edit-window of echarts should be added to create the requestet URL by clicking on it.

**Comment by Berchemer** [comment]
Now I saw there are two buttons in the options-Tab...
Sorry 🤦‍♂️
