### ISSUE TITLE
Tooltip zeigt nur noch einen Wert

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.echarts#33]
Nach Update auf die Version 0.4.13 wird im Tooltip nur noch ein Messwert angezeigt.
Nach Downgrad auf Version 0.4.11 werden wieder alle Messwerte im Tooltip angezeigt.
Tooltip mit V 0.4.13
![image](https://user-images.githubusercontent.com/35137293/112758051-a3e9e280-8fec-11eb-809e-cbc1c09b862d.png)
Tooltip mit V 0.4.11
![image](https://user-images.githubusercontent.com/35137293/112758056-ac421d80-8fec-11eb-958e-822975d12af8.png)

Gruß Steffen

Edit: Gerade mal die 0.4.12 getestet, dort wird auch nur ein Messwert im Tooltip angezeigt

**Comment by Parodontitis** [comment]
Die Timestamps haben bei mir Unterschiede im Milisekunden-Bereich, Das führt dazu, dass sie nie gleichzeitig in Tooltip angezeigt werden. 
@GermanBluefox - Könnte man das nicht irgendwie runden? Entweder auf der Tooltip oder auf der TS Seite? Offensichtlich bin ich Depp nicht der einziger der damit Probleme hat.

**Comment by Steff42** [comment]
works now as expected!

thx Steffen
