### ISSUE TITLE
Presets und Ordner verschwinden bei Änderung der Benennung

### ISSUE THREAD

**Issue by sohejl** [ioBroker/ioBroker.echarts#39]
**Describe the bug**  
Presets und Ordner verschwinden einfach, sobald man den Name Ändert.
Beispiel:
- neues Preset mit beliebigen Datenpunkten wird angelegt, der Name wird dann ja automatisch generiert *preset 1*
- klickt man auf das Stift Symbol wird der Dialog zu Benennungsänderung angezeigt
- hier wird dann ein neuer Name eingegeben und das Feld zur Bestätigung "umbenennen" wird grün
- sobald man darauf klickt, verschwindet das Dialogfeld und ebenso das Preset aus der Liste
- das Diagramm bleibt zusehen bis man eine andere Aktion durchführt

**To Reproduce**  
- neues Preset mit beliebigen Datenpunkten wird angelegt, der Name wird dann ja automatisch generiert *preset 1*
- klickt man auf das Stift Symbol wird der Dialog zu Benennungsänderung angezeigt
- hier wird dann ein neuer Name eingegeben und das Feld zur Bestätigung "umbenennen" wird grün
- sobald man darauf klickt, verschwindet das Dialogfeld und ebenso das Preset aus der Liste

**Expected behavior**  
Normlerweise solle das Preset ja in der Liste verbleiben und einfach mit dem neuen Namen angegeben werden.

**Screenshots & Logfiles**  
![Screenshot 2021-04-22 224614](https://user-images.githubusercontent.com/83038892/115783192-d7861580-a3bc-11eb-9813-144f9f026137.png)
![Screenshot 2021-04-22 224652](https://user-images.githubusercontent.com/83038892/115783196-d81eac00-a3bc-11eb-828e-97d805d768b8.png)
![Screenshot 2021-04-22 224712](https://user-images.githubusercontent.com/83038892/115783197-d81eac00-a3bc-11eb-9ace-1fed047e5d82.png)
![Screenshot 2021-04-22 224726](https://user-images.githubusercontent.com/83038892/115783199-d8b74280-a3bc-11eb-9f78-1dd6f1115131.png)

**Versions:**  
 - Adapter version: 0.4.13
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1
 - Operating system: raspian

**Additional context**  
Es lief früher einmal problemlos. Die einzige Änderung die ich zwischenzeitlich in iobroker gemacht habe war die Installation des modbus adapters und zeitweise installation des blockly adapter.

Wäre toll wenn es eine Lösung dazu gäbe. Deinstallation - Neustart raspi und dann neue Installation des echarts adapters habe ich bereits ohne Erfolg versucht.

**Comment by itProfi** [comment]
Same problem

**Comment by GermanBluefox** [comment]
Kann es sein, dass Admin5 benutzt wird? Falls ja, ist gefixt in 5.0.9

**Comment by Guenda85** [comment]
ich bekomme 5.0.9 noch gar nicht zum Update?

**Comment by itProfi** [comment]
> Kann es sein, dass Admin5 benutzt wird? Falls ja, ist gefixt in 5.0.9

In version 5.0.10 - fix this error, but if click on this button, all disappear..
![Скриншот 28-04-2021 121121](https://user-images.githubusercontent.com/6728198/116378934-3c0cfe80-a81b-11eb-8abe-b47c354a9114.jpg)

**Comment by GermanBluefox** [comment]
Und jetzt?

**Comment by sohejl** [comment]
Hi, habe eben das Update auf den admin adapter 5.0.10 gemacht, damit scheint sich das Problem erledigt zu haben. Sowohl Charts als auch Ordner können umbenannt werden und bleiben sichtbar.

Besten dank.

**Comment by sohejl** [comment]
Damit würde ich das issue dann auch schließen.
