### ISSUE TITLE
Echarts 0.4.14 - theme not assign..

### ISSUE THREAD

**Issue by itProfi** [ioBroker/ioBroker.echarts#41]
Admin 5.0.10, echarts 0.4.14 - button with theme's names not apply to charts..
![Скриншот 29-04-2021 144207](https://user-images.githubusercontent.com/6728198/116545687-63d29400-a8f9-11eb-93ca-6b55a0e9c761.jpg)
![Скриншот 29-04-2021 144138](https://user-images.githubusercontent.com/6728198/116545692-646b2a80-a8f9-11eb-9e37-89d8e91365bc.jpg)

**Comment by GermanBluefox** [comment]
Cannot reproduce. Can you try 1.0.0?
