### ISSUE TITLE
Presets disapear when renaming or moving

### ISSUE THREAD

**Issue by RK62** [ioBroker/ioBroker.echarts#45]
When I rename a preset, it is no longer visible in the list and it seems it is deleted. The same behavior occurs when I try to move a preset.

On my ioBroker test system the problem does not occur. Newer adapters are in use here and there are significantly fewer presets.

The adapter is really great. Feel free to ask if more information is needed. 

Thanks, Ralf

**Versions:**  
- Adpater Admin 4.2.1, 
- Adapter eCharts 0.4.14
 - JS-Controller version: 3.2.16
 - Node version:v12.20.2
 - Operating system: Debian on Docker
 - Redis v6.2.1

**Comment by uelpenich** [comment]
Ich habe das gleiche Problem (When I rename a preset, it is no longer visible in the list and it seems it is deleted) nach dem Update des Adapters eCharts von Version 0.4.11 nach Version 0.4.14 beobachtet. 
Weiterhin sind die Objekte "echarts.0" nicht mehr sichtbar. Sie waren definitiv unter der Version 0.4.11 zu sehen. 
![Objekte](https://user-images.githubusercontent.com/63613798/121426610-13c50380-c974-11eb-8233-fd3ee1cdb708.jpg)

Nach dem Rückgang zur eCharts Version 0.4.11 ist das Umbenennen der Presets und Charts wieder möglich. 
Die Objekte "echarts.0" sind weiterhin nicht mehr sichtbar.

**Comment by uelpenich** [comment]
Die Objekte "echarts.0" kontte ich wieder sichtbar machen, indem ich
- in der Objektliste die Instanz "echarts" (das Objekt "system.adapter.echarts.0" mit allem darunter liegendem Inhalt) gelöscht habe
![Instanz echarts löschen](https://user-images.githubusercontent.com/63613798/121436948-c059b200-c981-11eb-9ea2-fb7c405d19cd.jpg)

- beim Adapter "E-Charts" eine neue Instanz erzeugt habe
![E-Charts Adapter](https://user-images.githubusercontent.com/63613798/121436971-ccde0a80-c981-11eb-9520-3621972bcbe4.jpg)
![E-Charts Adapter Instanz hinzufügen](https://user-images.githubusercontent.com/63613798/121436987-d49daf00-c981-11eb-9ff5-d2c7433f9c49.jpg)
- unter ECharts jedes existierende Chart einmal umbenannt habe.
![Chart Umbenennen](https://user-images.githubusercontent.com/63613798/121436998-d9faf980-c981-11eb-9189-9dc5f5137c91.jpg)
Danach waren alle echarts.0 Objekte wieder vorhanden:
![alle echarts Obkekte wieder da](https://user-images.githubusercontent.com/63613798/121437009-dd8e8080-c981-11eb-8b60-ed60ec8272a2.jpg)

**Comment by RK62** [comment]
Bei mir heute das gleiche Verhalten: 
- In den Objekten gibt es die Gruppe echarts.0 nicht mehr 
- Lösung oben (Umbenennen) traue ich mich nicht weil die Einstellungen dann vielleicht ganz weg sind
- Sobald ich eine Einstellung innerhalb ECharts an einer Grafik verändere, wird das Objekt für diese Grafik wieder angelegt

**Comment by uelpenich** [comment]
> 
> 
> Bei mir heute das gleiche Verhalten:
> 
>     * In den Objekten gibt es die Gruppe echarts.0 nicht mehr
_Das Löschen der Instanz und das Neuanlegen hat mir die Gruppe zurück gebracht. Dabei sind alle Charts erhalten geblieben._ 
> 
>     * Lösung oben (Umbenennen) traue ich mich nicht weil die Einstellungen dann vielleicht ganz weg sind
_. . . mit etwas Unwichtigem (Preset oder Kopie eines Presets) probieren . . ._
> 
>     * Sobald ich eine Einstellung innerhalb ECharts an einer Grafik verändere, wird das Objekt für diese Grafik wieder angelegt
_Ja, bei mir auch, aber ohne sie einer Gruppe echarts.0 zuzuordnen. Nach einem Browserrefresh (F5) waren sie dann wieder weg. 
Es ist egal, ob man das Chart umbenennt oder etwas am Chart ändert, der Effekt ist der gleiche: nach dem Sichern ist das Chart wieder da._

**Comment by RK62** [comment]
Das "Verschwinden" der States im Admin konnte ich bei mir aufklären:
Wenn die Anzeige der Objekte mit Datum aktiviert wird (![image](https://user-images.githubusercontent.com/39200469/122463216-9faedf00-cfb5-11eb-97ed-b927b6172a17.png)), werden die Objekte nicht mehr angezeigt weil sie kein Datum haben. 

Das Verschwinden der Einträge in echarts bei Namensänderung oder Verschieben bleibt jedoch bestehen. Zumindest kann ich jetzt über Anpassung der Objekte im Raw-Modus Charts umbenennen und verschieben.

**Comment by uelpenich** [comment]
>  Zumindest kann ich jetzt über Anpassung der Objekte im Raw-Modus Charts umbenennen und verschieben.

? wie komme ich an das Objekt im Raw-Modus, wenn keine echarts.0 Objekte angezeigt werden ?

**Comment by RK62** [comment]
Siehe oben: Wenn ich die „1“ im Admin abschalte sehe ich den Objektbaum echarts.0

**Comment by uelpenich** [comment]
Bei mir sind zwei Einstellungen erforderlich:

- Bei der Anzeige der Objekte Datum deaktivieren
- Experten Modus ein

perten Modus
![grafik](https://user-images.githubusercontent.com/63613798/122669637-98a6ed00-d1be-11eb-97e5-cc37c0343ba7.png)

**Comment by RK62** [comment]
Ist unter V1.0.3 behoben, Danke für die Arbeit!
