### ISSUE TITLE
No selection of datapoint-IDs possible, blank screen only

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.echarts#466]
Hi, 
with 1.6.1 I get a blank page if trying to select a datapoint ID from the list of datapoints with influxdb. (In my case v2)

To reproduce:
- add a new datasource 
- try to select a data from the list of influxdb-enabled datapoints in the field ID

Than complete blank (white) screen, no datasources-IDs available :-(

Was working before (last used around 3 days ago). No changes made to database, only some new points added/enabled.
I can cut_n_paste the datapoint representation into the ID field, that works.

Display of echarts with manually added datasource-ID works!

cu
Harvey

**Comment by Norb1204** [comment]
I can confirm this, I have the same problem

**Comment by harvey637** [comment]
reverting to 1.5.4 :::: THIS IS WORKING !

**Comment by GermanBluefox** [comment]
https://www.iobroker.net/#de/documentation/faq/_040_contibution.md?fehlerindergrafischeoberflchemelden

**Comment by GermanBluefox** [comment]
Bitte 1.7.0 testen. Wird in latest heute Nachmittag.

**Comment by afuerhoff** [comment]
siehe https://github.com/ioBroker/ioBroker.echarts/issues/469

**Comment by harvey637** [comment]
seit 1.7.1 ok
