### ISSUE TITLE
Bar chart

### ISSUE THREAD

**Issue by eifel-tech** [ioBroker/ioBroker.echarts#49]
It would be nice for some data like energy in a month to show them as bar chart. I would be glad if there comes a suitable diagram type :-)

**Comment by DerDoubleD** [comment]
+1 Würde mich sehr darüber freuen

**Comment by Wondermusic** [comment]
+1 I agree. That would be great. :)

**Comment by Apollon77** [comment]
@Wondermusic Thumbs up in first post is the way to show interest not +1 posts

**Comment by Chris-1965** [comment]
+1 would be great

**Comment by Apollon77** [comment]
@Chris-1965 Thumbs up on fist post is compltely enough to show interest. me too posts are not helpful

**Comment by GermanBluefox** [comment]
Implemented in 1.4.0

**Comment by Chris-656** [comment]
really great work thx a lot
regards Chris
