### ISSUE TITLE
Fehlermeldung CORS (Cross-Origin Resource Sharing)

### ISSUE THREAD

**Issue by vowill** [ioBroker/ioBroker.echarts#519]
Das fully-browser-Log liefert regelmäßig den Eintrag
'[ERROR] Access to fetch at 'https://...' from origin 'http://192.168.0.65:8082' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. -- on line 0 of http://192.168.0.65:8082/echarts/index.html?preset=echarts.0.Wind%20und%20Regen&noBG=false'
Zudem wird das Chart bei erneuter Aktivierung derselben vis-Seite oftmals nicht angezeigt.

Vermutlich muss im Header von main.js des ECharts-Adapters eine Anweisung 'crossDomain: true' ergänzt werden.

Verwendete Adapter-Version ECharts: v1.5.4
JS-Controller version: 5.0.16
Node version: v16.15.1
Im Tablet:
  - Verwendete App-Version des Fully-Browsers auf Android: 1.54.1-play
  - Webview provider: com.android.webview, Webview version 95.0.4638.74

**Comment by Apollon77** [comment]
What is port 8082 in your system? web? or socketio? or ws?

**Comment by vowill** [comment]
Port 8082 is in use by vis. However I just realize that my WebView version (95.0.4638.74) is completely outdated --> I need to correct this. The other tablets with updated WebView are running fine.
--> Please mark this issue as 'closed'.
Sorry for causing trouble here ...

**Comment by vowill** [comment]
WebView is outdated; could have caused the issue.
