### ISSUE TITLE
Option "Kein Hintergrund" funktioniert in v1.0.0 nicht mehr

### ISSUE THREAD

**Issue by rrov1** [ioBroker/ioBroker.echarts#53]
Seit der Version 1.0.0 des eCharts Adapter funktioniert die Option "Kein Hintergrund" nicht mehr. In der Visualisierung wird ein weißer Hintergrund angezeigt. Wenn auf den Adapter v0.4.14 downgraded funktioniert alles wieder.

1. Chart öffnen
2. TAB: Erscheinung
3. Option: "Kein Hintergrund" -> aktivieren

**Expected behavior**  
Die Hintergrundfarbe der Visualisierung wird verwendet/dargestellt.

**Versions:**  
 - Adapter version: 1.0.0
 - JS-Controller version: 3.3.14
 - Node version: 12.20.1
 - Operating system: 5.4.119-1-pve # 1 SMP PVE 5.4.119-1 (Tue, 01 Jun 2021 15:32:00 +0200) x86_64 GNU/Linux

**Comment by GermanBluefox** [comment]
Fixed in 1.0.1

**Comment by rrov1** [comment]
Adapter getestet, Fehler behoben.
Vielen Dank!
