### ISSUE TITLE
ECharts not loading user interface

### ISSUE THREAD

**Issue by MarvinMH** [ioBroker/ioBroker.echarts#54]
When clicking on the ECharts item on the main navigation panel, I just see the loading animation forever. No log messages indicating any error. I tried restarting ioBroker, restarting raspberry pi, full browser refresh, Firefox and Edge.

![grafik](https://user-images.githubusercontent.com/66381169/125197159-e4e4ca80-e25c-11eb-8731-21a33cd55c5b.png)

I'm happy to provide any more details if required.

Version: 1.0.0 from Github
JSController 3.2.16
Running on Raspbery Pi 4.
Browser: Firefox 89.0.2

**Comment by Chris-1965** [comment]
Is the same for me.
E-Charts keeps on loading with version 1.0.0
regards Chris

**Comment by GermanBluefox** [comment]
> Is the same for me.
> E-Charts keeps on loading with version 1.0.0
> 
> Tried also to downgrade to 0.4.14 and then to 1.0.0 also not worked for me.
> node:12.22.1
> nodejs:12.22.1
> JSController 3.2.16
> 
> regards Chris

Which admin version do you have?

**Comment by MarvinMH** [comment]
> 
> 
> > Is the same for me.
> > E-Charts keeps on loading with version 1.0.0
> > Tried also to downgrade to 0.4.14 and then to 1.0.0 also not worked for me.
> > node:12.22.1
> > nodejs:12.22.1
> > JSController 3.2.16
> > regards Chris
> 
> Which admin version do you have?

I'm not Chris but my Admin version is 4.2.1.

**Comment by Chris-1965** [comment]
> 
> 
> > Is the same for me.
> > E-Charts keeps on loading with version 1.0.0
> > Tried also to downgrade to 0.4.14 and then to 1.0.0 also not worked for me.
> > node:12.22.1
> > nodejs:12.22.1
> > JSController 3.2.16
> > regards Chris
> 
> Which admin version do you have?

I also have 4.2.1 Admin Version
regards

**Comment by Chris-1965** [comment]
Tried also Version 1.0.1 the same issue.
regards Chris

**Comment by Baenker** [comment]
Bei mir selbes Problem. Mit V1.01 vom Adapter. Admi 4.21. Nach Downgrade funktioniert es wieder.

Im Forum habe ich gelesen das es bei jemanden mit Admi 5.x funktioniert. 

Vermutlich Breaking Change mit V1.x ?

**Comment by GermanBluefox** [comment]
Please test 1.0.2

**Comment by MarvinMH** [comment]
1.0.2 works. Thanks!

**Comment by Baenker** [comment]
Funktioniert bei mir auch wieder. issue sollte geschlossen werden
