### ISSUE TITLE
no more working starting from 0.3.x

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.echarts#6]
![eCharts_error](https://user-images.githubusercontent.com/11257222/99712649-a7e87f80-2aa3-11eb-978b-579315bb9308.png)
today I updated my test installation from 0.1.2 to 0.3.6
it didn't work anymore.
Deleting and reinstalling didn't help. So I startet in all steps from the beginning to 0.2.0 it works.
newer versions fail to load the chart.

in the browser console is said:  Cannot send ready event to parent window;    instrument.ts:129
and: [Violation] 'setTimeout' handler took 123ms;     2.c4a6d9df.chunk.js:2

last information is:  [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952;     trycatch.ts:185

HTH
Rainer

**Comment by GermanBluefox** [comment]
I really cannot reproduce it and other users reports, that it works for them...

**Comment by Homoran** [comment]
Can I provide some more  information to help to reproduce?

At the moment the installation is not online due to some construction works in my working room :-(
They will last at least three days.

After that I can reactivate the machine

**Comment by GermanBluefox** [comment]
No. Just retry new versions

**Comment by Homoran** [comment]
Today I could try with 0.4.2 with the same result.

Honestly, I have to tell I installed it on a Cubietruck
The errors stay the same:

`VM115 2.08121cc9.chunk.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ VM115 2.08121cc9.chunk.js:2
(anonymous) @ VM115 2.08121cc9.chunk.js:2
(anonymous) @ VM115 2.08121cc9.chunk.js:2
ol @ VM115 2.08121cc9.chunk.js:2
vs @ VM115 2.08121cc9.chunk.js:2
t.unstable_runWithPriority @ VM115 2.08121cc9.chunk.js:2
Vo @ VM115 2.08121cc9.chunk.js:2
ms @ VM115 2.08121cc9.chunk.js:2
Zl @ VM115 2.08121cc9.chunk.js:2
(anonymous) @ VM115 2.08121cc9.chunk.js:2
t.unstable_runWithPriority @ VM115 2.08121cc9.chunk.js:2
Vo @ VM115 2.08121cc9.chunk.js:2
qo @ VM115 2.08121cc9.chunk.js:2
$o @ VM115 2.08121cc9.chunk.js:2
Kl @ VM115 2.08121cc9.chunk.js:2
enqueueSetState @ VM115 2.08121cc9.chunk.js:2
w.setState @ VM115 2.08121cc9.chunk.js:2
(anonymous) @ VM116 main.fae88f63.chunk.js:1
18:24:55.385 index.js:83 [Violation] 'message' handler took 162ms
18:24:56.170 VM122 main.5b8b01d6.chunk.js:1 iobroker.echarts-show@0.4.2 using theme "colored"
18:24:57.817 VM121 2.3bc6621a.chunk.js:2 Cannot send ready event to parent window
(anonymous) @ VM121 2.3bc6621a.chunk.js:2
(anonymous) @ VM122 main.5b8b01d6.chunk.js:1
Promise.then (async)
onReady @ VM122 main.5b8b01d6.chunk.js:1
(anonymous) @ VM121 2.3bc6621a.chunk.js:2
Promise.then (async)
(anonymous) @ VM121 2.3bc6621a.chunk.js:2
value @ VM121 2.3bc6621a.chunk.js:2
value @ VM121 2.3bc6621a.chunk.js:2
value @ VM121 2.3bc6621a.chunk.js:2
(anonymous) @ VM121 2.3bc6621a.chunk.js:2
r.onack @ VM119 socket.io.js:8
r.onpacket @ VM119 socket.io.js:8
(anonymous) @ VM119 socket.io.js:8
r.emit @ VM119 socket.io.js:6
r.ondecoded @ VM119 socket.io.js:6
(anonymous) @ VM119 socket.io.js:8
r.emit @ VM119 socket.io.js:6
a.add @ VM119 socket.io.js:6
r.ondata @ VM119 socket.io.js:6
(anonymous) @ VM119 socket.io.js:8
r.emit @ VM119 socket.io.js:6
r.onPacket @ VM119 socket.io.js:7
(anonymous) @ VM119 socket.io.js:7
r.emit @ VM119 socket.io.js:6
r.onPacket @ VM119 socket.io.js:7
r.onData @ VM119 socket.io.js:7
ws.onmessage @ VM119 socket.io.js:8
18:25:04.533 VM115 2.08121cc9.chunk.js:2 [Violation] 'message' handler took 406ms
18:25:06.308 VM115 2.08121cc9.chunk.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ VM115 2.08121cc9.chunk.js:2
(anonymous) @ VM115 2.08121cc9.chunk.js:2
(anonymous) @ VM115 2.08121cc9.chunk.js:2
ol @ VM115 2.08121cc9.chunk.js:2
vs @ VM115 2.08121cc9.chunk.js:2
t.unstable_runWithPriority @ VM115 2.08121cc9.chunk.js:2
Vo @ VM115 2.08121cc9.chunk.js:2
ms @ VM115 2.08121cc9.chunk.js:2
Zl @ VM115 2.08121cc9.chunk.js:2
(anonymous) @ VM115 2.08121cc9.chunk.js:2
t.unstable_runWithPriority @ VM115 2.08121cc9.chunk.js:2
Vo @ VM115 2.08121cc9.chunk.js:2
qo @ VM115 2.08121cc9.chunk.js:2
$o @ VM115 2.08121cc9.chunk.js:2
Kl @ VM115 2.08121cc9.chunk.js:2
enqueueSetState @ VM115 2.08121cc9.chunk.js:2
w.setState @ VM115 2.08121cc9.chunk.js:2
(anonymous) @ VM116 main.fae88f63.chunk.js:1
18:26:20.589 admin.js:1484 clear
18:26:20.675 admin.js:1291 Subscribe: system.host.*
18:26:23.182 adminAdapters.js:421 [Violation] 'setTimeout' handler took 1592ms
18:26:23.292 [Violation] Forced reflow while executing JavaScript took 268ms
18:26:24.151 Blocked current origin from receiving cross-site document at https://github.com/hombach/ioBroker.kostal-piko-ba/blob/master/admin/picoba.png with MIME type text/html.
Image (async)
(anonymous) @ jquery-3.2.1.min.js:3
W @ jquery-3.2.1.min.js:3
html @ jquery-3.2.1.min.js:3
(anonymous) @ adminAdapters.js:1281
setTimeout @ adminAdapters.js:703
setTimeout (async)
Adapters.getAdaptersInfo @ adminAdapters.js:700
Adapters._postInit @ adminAdapters.js:836
inited.e.main.objectsLoaded.main.tabs.hosts.getHosts @ adminAdapters.js:1453
(anonymous) @ adminHosts.js:612
r.onack @ index.js:83
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83
18:26:24.166 Blocked current origin from receiving cross-site document at https://github.com/Grizzelbee/ioBroker.mielecloudservice/blob/master/admin/mielecloudservice.svg with MIME type text/html.
Image (async)
(anonymous) @ jquery-3.2.1.min.js:3
W @ jquery-3.2.1.min.js:3
html @ jquery-3.2.1.min.js:3
(anonymous) @ adminAdapters.js:1281
setTimeout @ adminAdapters.js:703
setTimeout (async)
Adapters.getAdaptersInfo @ adminAdapters.js:700
Adapters._postInit @ adminAdapters.js:836
inited.e.main.objectsLoaded.main.tabs.hosts.getHosts @ adminAdapters.js:1453
(anonymous) @ adminHosts.js:612
r.onack @ index.js:83
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83
18:26:47.253 adminAdapters.js:421 [Violation] 'setTimeout' handler took 52ms`

Can it be a timeout due to slow hardware?

**Comment by GermanBluefox** [comment]
I added in 0.4.3 the error message. Please update, try again and paste the error here.

**Comment by GermanBluefox** [comment]
@Homoran ?

**Comment by Homoran** [comment]
Sorry, I had been offline on the PC for some days :-(
Now I upgraded to 0.4.5

I couldn't believe the error messsage. it  was 
```
host.cubietruck | 2020-12-11 17:26:16.123 | error | startInstance system.adapter.echarts.0: required adapter "web" not found!
```

So I installed the web-adapter but it didn't help.
I cannot find any other error messages although i changed the loglevel of the instance to debug.
The status dot of the instance stays red, telling connection to host - false; alive - false.

So I will try out some things and comment again

**Comment by GermanBluefox** [comment]
Please test 0.4.6

**Comment by Homoran** [comment]
I did!
There is a difference. The x- and Y-axis appear for a second and after this it's nearly the same.
The errormessages in the browser console are different:
![echarts error_all](https://user-images.githubusercontent.com/11257222/102017354-c8d08780-3d66-11eb-899c-27d633df2d88.png)

but finally it still doesn't work

Sorry for bad news :-(

**Comment by GermanBluefox** [comment]
> But I'm wondering why. Up to 0.2.x it works reproducable

Because I changed the communication way. Please test one more time with iobroker.echarts@0.4.8

**Comment by Homoran** [comment]
**GREAT!**
It works!

there are only two little things:
In the browser console appears
`instrument.ts:129 Cannot read : The id is empty! Please provide a valid id.`
what I cannot relate to anything.

And after update to 0.3.8, the version stays at 0.3.7

Thanks again a lot for your efforts!
I wish you and your family a healthy, merry christmas!

**Comment by GermanBluefox** [comment]
> In the browser console appears
> `instrument.ts:129 Cannot read : The id is empty! Please provide a valid id.`

Will the chart be shown?

**Comment by Homoran** [comment]
Yes, the chart is shown.
Generally, it works - great job again!
