### ISSUE TITLE
Fehler bei mehreren Markierungen

### ISSUE THREAD

**Issue by hopedotz** [ioBroker/ioBroker.echarts#62]
Wenn ich mehrere Markierungen für eine Chart habe, wird mir immer nur eine angezeigt:

![grafik](https://user-images.githubusercontent.com/70532718/136534179-8f43c13f-c505-4694-983c-a9e3c845a884.png)

**Comment by uelpenich** [comment]
Ich habe da kein Problem (Echarts Version 0.4.14)
Du hast die automatische Y-Achsen Skalierung gewählt, und damit liegt eine Markierung ausserhalb des Bereiches. Weiterhin könnte die Deckkraft 1.0 der Füllung und eine ungeschckte Farbwahl eine Markierung unsichtbar machen. 
![grafik](https://user-images.githubusercontent.com/63613798/136555694-8d42664a-f18c-40bd-baeb-b563346551a1.png)
