### ISSUE TITLE
Update Fehler

### ISSUE THREAD

**Issue by mcreuter** [ioBroker/ioBroker.echarts#634]
[2024-06-19T07_46_53_251Z-debug-0.log](https://github.com/user-attachments/files/15897297/2024-06-19T07_46_53_251Z-debug-0.log)

Updatefehler von V 1.7.2 zu 1.8.3

Updatelog:

$ iobroker upgrade echarts@1.8.3 --debug

Update echarts from @1.7.2 to @1.8.3

Installing iobroker.echarts@1.8.3... (System call)

npm error code ETARGETnpm error notarget No matching version found for iobroker.echarts@1.8.3.npm error notarget In most cases you or one of your dependencies are requestingnpm error notarget a package version that doesn't exist.

npm error A complete log of this run can be found in: /opt/iobroker/.npm/_logs/2024-06-19T07_46_53_251Z-debug-0.log

Adapter "system.adapter.vis-2.0" restarted.

upload [17] echarts /opt/iobroker/node_modules/iobroker.echarts/www/asset-manifest.json asset-manifest.json application/json

upload [12] echarts /opt/iobroker/node_modules/iobroker.echarts/www/preview/favicon.ico preview/favicon.ico image/vnd.microsoft.icon

upload [11] echarts /opt/iobroker/node_modules/iobroker.echarts/www/preview/index.html preview/index.html text/html

upload [10] echarts /opt/iobroker/node_modules/iobroker.echarts/www/preview/manifest.json preview/manifest.json application/json

upload [9] echarts /opt/iobroker/node_modules/iobroker.echarts/www/preview/static/css/main.e631bfb5.css preview/static/css/main.e631bfb5.css text/css

upload [7] echarts /opt/iobroker/node_modules/iobroker.echarts/www/preview/static/js/main.1b756fe6.js preview/static/js/main.1b756fe6.js application/javascript

upload [6] echarts /opt/iobroker/node_modules/iobroker.echarts/www/preview/static/js/main.1b756fe6.js.LICENSE.txt preview/static/js/main.1b756fe6.js.LICENSE.txt text/plain

upload [5] echarts /opt/iobroker/node_modules/iobroker.echarts/www/preview/static/js/main.1b756fe6.js.map preview/static/js/main.1b756fe6.js.map application/json

upload [4] echarts /opt/iobroker/node_modules/iobroker.echarts/www/static/css/main.e631bfb5.css static/css/main.e631bfb5.css text/css

upload [3] echarts /opt/iobroker/node_modules/iobroker.echarts/www/static/css/main.e631bfb5.css.map static/css/main.e631bfb5.css.map application/json

upload [2] echarts /opt/iobroker/node_modules/iobroker.echarts/www/static/js/main.2b7495c2.js static/js/main.2b7495c2.js application/javascript

upload [1] echarts /opt/iobroker/node_modules/iobroker.echarts/www/static/js/main.2b7495c2.js.LICENSE.txt static/js/main.2b7495c2.js.LICENSE.txt text/plain

upload [0] echarts /opt/iobroker/node_modules/iobroker.echarts/www/static/js/main.2b7495c2.js.map static/js/main.2b7495c2.js.map application/json

upload [28] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/asset-manifest.json asset-manifest.json application/json

upload [20] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/chart/static/js/main.2b7495c2.js.LICENSE.txt chart/static/js/main.2b7495c2.js.LICENSE.txt text/plain

upload [19] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/chart/static/js/main.2b7495c2.js.map chart/static/js/main.2b7495c2.js.map application/json

upload [18] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/echarts.png echarts.png image/png

upload [17] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/favicon.ico favicon.ico image/vnd.microsoft.icon

upload [16] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/manifest.json manifest.json application/json

upload [15] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/preview/asset-manifest.json preview/asset-manifest.json application/json

upload [14] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/preview/favicon.ico preview/favicon.ico image/vnd.microsoft.icon

upload [13] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/preview/index.html preview/index.html text/html

upload [12] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/preview/manifest.json preview/manifest.json application/json

upload [11] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/preview/static/css/main.e631bfb5.css preview/static/css/main.e631bfb5.css text/css

upload [10] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/preview/static/css/main.e631bfb5.css.map preview/static/css/main.e631bfb5.css.map application/json

upload [9] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/preview/static/js/main.1b756fe6.js preview/static/js/main.1b756fe6.js application/javascript

upload [8] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/preview/static/js/main.1b756fe6.js.LICENSE.txt preview/static/js/main.1b756fe6.js.LICENSE.txt text/plain

upload [7] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/preview/static/js/main.1b756fe6.js.map preview/static/js/main.1b756fe6.js.map application/json

upload [6] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/static/css/main.610065eb.css static/css/main.610065eb.css text/css

upload [5] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/static/css/main.610065eb.css.map static/css/main.610065eb.css.map application/json

upload [4] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/static/js/main.245b61c0.js static/js/main.245b61c0.js application/javascript

upload [3] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/static/js/main.245b61c0.js.LICENSE.txt static/js/main.245b61c0.js.LICENSE.txt text/plain

upload [2] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/static/js/main.245b61c0.js.map static/js/main.245b61c0.js.map application/json

upload [1] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/tab.html tab.html text/html

upload [0] echarts.admin /opt/iobroker/node_modules/iobroker.echarts/admin/vendor/socket.io.js vendor/socket.io.js application/javascript

Process exited with code 0

**Comment by Apollon77** [comment]
naja eine 1.8.3 gibts nicht :-) Wurde wegen Fehler nicht gepublished, sollte aber auch in keinem repo sein

**Comment by mcreuter** [comment]
> naja eine 1.8.3 gibts nicht :-) Wurde wegen Fehler nicht gepublished, sollte aber auch in keinem repo sein

wurde mir ganz normal zum Update unter den Adaptern angeboten... Was soll ich sagen 😉
