### ISSUE TITLE
Can available presets be fetched programmatically (e.g. via SimpleAPI or simple HTTP Request)?

### ISSUE THREAD

**Issue by peter9teufel** [ioBroker/ioBroker.echarts#635]
**Is your feature request related to a problem? Please describe.**
I'm working on a client app (Android, iOS) for ioBroker. Users are requesting support for echarts but I was not able to find a way to request available presets via simple-api (no datapoints in the object tree for echarts) or via HTTP Request (plain http) to present the user a list of available presets and enable him to embed the desired echarts in the app dashboard.

**Describe the solution you'd like**
Another way could be, that the echarts adapter creates a datapoint in the objects tree under echarts.0 for each preset providing the preset name. This way, those information would be available the same way like all the other datapoints that can be used in my client. Using the preset name and the ioBroker IP I would be able to simply compose the URL to the echart to embed it in the client app.

**Describe alternatives you've considered**
URL path to be queried via http to get the names of all available echarts presets.

Thanks and best regards,
Peter

**Comment by Apollon77** [comment]
The object type for echart settings is "chart", you might need to specify the obejct type because it is not "state" which is used as default

**Comment by GermanBluefox** [comment]
The presets can be read here:
![image](https://github.com/user-attachments/assets/881a88b0-b6df-4842-aebb-dc231866c5ac)
