### ISSUE TITLE
Falls unter ID ein nicht vorhandenes Objekt eingetragen ist, wird der Objektbrowser mit einer leeren Seite geöffnet 

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.echarts#636]
**Describe the bug**  
Objektbrowser lässt sich nicht aufrufen, falls ein nicht vorhandener Datenpunkt unter ID eingetragen ist.

**To Reproduce**  
Irgendeinen Text in ID eintragen und dann den Objektbroser aufrufen.

**Expected behavior**  
Objektbrowser startet normal

**Screenshots & Logfiles**  
Console:
![image](https://github.com/ioBroker/ioBroker.echarts/assets/50245893/a30c13d2-d930-4ad8-946d-9cc24aa9dfb0)

Vor dem Aufruf des Objektbrowsers mit nicht vorhandenem Datenpunkt:
![image](https://github.com/ioBroker/ioBroker.echarts/assets/50245893/b392ac01-e125-48c8-a535-db77e8b82134)

Nach Aufruf des Objektbrowsers:
![image](https://github.com/ioBroker/ioBroker.echarts/assets/50245893/c9cbace8-4c64-4c50-9d24-494fcbda5854)

**Versions:**  
 - Adapter version: 1.8.4
 - JS-Controller version: 5.0.19
 - Node version: 20.14.0
 - Operating system: Debian 12 - Proxmox

**Additional context**  
-

**Comment by GermanBluefox** [comment]
Sollte mit neueste version gefixt sein

**Comment by afuerhoff** [comment]
Funktioniert. Danke
