### ISSUE TITLE
 e-charts 1.9.0 zeigt keine Diagramme mehr

### ISSUE THREAD

**Issue by FrazerDungeon** [ioBroker/ioBroker.echarts#679]
ich habe den e-charts Adapter auf 1.9.0 aktualisiert und getestet.
Seitdem zeigen die Widget in der VIS-2 keinen Inhalt mehr an.
Das gilt für schon bestehende Widgets und e-charts-Preset.
Wenn man beides neu macht, werden wieder Diagramme angezeigt.
Ich habe auch bestehende Preset aktualisiert. Das hat nichts geholfen.

/usr/bin/nodejs v20.16.0
/usr/bin/node v20.16.0
/usr/bin/npm 10.8.1
/usr/bin/npx 10.8.1
/usr/bin/corepack 0.28.2
js-controller 6.0.10
admin 7.0.23

**Comment by GermanBluefox** [comment]
Bitte Browser Console zeigen: https://www.iobroker.net/#de/documentation/faq/_040_contibution.md?fehlerindergrafischeoberflchemelden

**Comment by FrazerDungeon** [comment]
![echarts_2](https://github.com/user-attachments/assets/7454841e-e324-457d-b4a3-c03f3c07ed80)
![echarts_1](https://github.com/user-attachments/assets/466724c4-48f7-417e-97e4-bb6f17be0ec0)

Die Bilder von oben stammen aus Chrom, das Bild von unten von Firefox.
Die Variable, die angemeckert wird, kommt aus css und funktioniert eigentlich. Sonst kann ich keine Fehler entdecken. 

![echarts_3](https://github.com/user-attachments/assets/0332be1e-d35f-4a53-9a84-342ba6cff119)
