### ISSUE TITLE
ECharts instance does not start after host update to version 6.0.9.

### ISSUE THREAD

**Issue by hgschwibbe** [ioBroker/ioBroker.echarts#680]
**Describe the bug**  
Echarts instance does not start after host update to version 6.0.9.

**To Reproduce**  
Install the updates

**Expected behavior**  
ECharts instance should start

**Screenshots & Logfiles**  
![Instanz](https://github.com/user-attachments/assets/5ac4fa48-4fb3-44a6-b079-38cc857b8024)
![Logs](https://github.com/user-attachments/assets/78130715-fcf9-4715-9130-e2a1bad1757f)

**Versions:**  
 - Adapter version: 1.7.2
 - JS-Controller version: 6.0.9
 - Node version: ECharts instance 
 - Operating system: pi os

**Comment by hgschwibbe** [comment]
File structure comparison shows that there is no @iobroker/adapter-core folder anymore in Host version 6.0.9:
![comparison](https://github.com/user-attachments/assets/802602fc-c196-4c00-a9cd-33851cd4a828)

**Comment by Apollon77** [comment]
Then something is strange. please reinstall echarts

**Comment by hgschwibbe** [comment]
Same issue, but all my charts are gone

**Comment by hgschwibbe** [comment]
"npm install iobroker.echarts@1.9.0" solved my problem.

Hopefully it does not cause further problems, because only 1.7.2 is supported by the adapter manager:
![echarts](https://github.com/user-attachments/assets/d3942d4f-d577-4057-b6ff-0bcd8d5f9dc1)

**Comment by mule1972** [comment]
Installed V1.8.4 from the beta repository which solved the issue too.

**Comment by klein0r** [comment]
> `npm install iobroker.echarts@1.9.0` solved my problem.

Looks like you execute those commands as root. This leads to permission issues (since the iobroker linux user is not able to modify those files). And you should avoid using `npm` directly!

1. Use `iobroker` cli to upgrade or install packages
2. Or execute those npm commands with the correct linux user (not recommended) e.g.

```bash
sudo -u iobroker npm install iobroker.echarts@1.9.0
```

Use the iobroker fixer to correct the permissions:

<img width="698" alt="Screenshot 2024-08-22 at 09 42 06" src="https://github.com/user-attachments/assets/81b24162-5b44-4b3f-9f9a-7e30d329abbc">

**Comment by hgschwibbe** [comment]
Yeah I already recognized it because iobroker was unable to open the database files so I had to execute the chmod command to make it right. But thanks for the hint.

**Comment by ltspicer** [comment]
Zur Info:
Hatte das gleiche Problem und wie empfohlen die eCharts V1.8.4 von der beta Repository installiert und das Problem scheint gelöst.
Mit der V1.9.0 war unterhalb des Charts (zBsp Datenquellen) das Fenster leer.
Leider zeigte eCharts V1.8.4 bei monatlichen Totalen (bei mir PV Total Monate >> bis 2 Jahre zurück) nichts mehr an.
Habe nun auf die offizielle V1.7.2 downgraded und siehe da, der host-Fehler ist nun auch weg.
Nun läuft es wieder wie gewohnt.
