### ISSUE TITLE
Offset wird zu Wert addiert

### ISSUE THREAD

**Issue by Farmer-cb** [ioBroker/ioBroker.echarts#69]
Hallo
habe gerade festgestellt, das der Offset den man beim Datenpunkt einstellen kann, beim Wert hinzuaddiert wird (ist das absicht)
in der Legende wird der Originalwert angezeigt
 siehe Screenshot: Hier wird in der Legende der Originalwert 7 angezeigt, im Tooltip und in der Grafik wird der Wert 7 + Offset 5 =12 angezeigt
![image](https://user-images.githubusercontent.com/38419234/143011797-e8dfc02b-f9c7-4368-aaf1-7edc8ee08e88.png)

**Comment by uelpenich** [comment]
Ich benutze den Offset bei der Darstellung von Binärwerten (z. B. Fesnter offen), um die "Kurve" an der richtigen Stelle des Diagramms darzustellen.
