### ISSUE TITLE
Ab v1.9.0 keine Balkendiagramme mehr!

### ISSUE THREAD

**Issue by BRoeske** [ioBroker/ioBroker.echarts#699]
Ich habe ebenfalls den e-charts Adapter auf 1.9.0 aktualisiert und seit dem werden keine Balkendiagramme mehr dargestellt. Alle anderen Typen funktionieren, nur bei Auswahl "Bar" bleibt alles leer.

Beispiel Typ "Line":
![echarts_line](https://github.com/user-attachments/assets/6cfc72a9-8f0c-4529-8ae8-05b0d65842ce)

Beispiel Typ "Bar" mit der selben Datenquelle:
![echarts_bar](https://github.com/user-attachments/assets/236d5cf6-098b-40d4-9b22-3ed3bc33a55e)

Ausserdem werden jetzt alle Hover-Details ausschliesslich auf weissem Hintergrund dargestellt. Vorher konnte man wenigstens diesen Hintergrund noch über ein geeignetes Thema beeinflussen, das geht jetzt nicht mehr ... immer weiss und in meinem Fall somit nahezu unbrauchbar.

Möglicherweise mache ich selbst was falsch, aber egal an welchen Werten ich drehe oder welche Datenquellen ich benutze, Balklendiagramme bleiben immer leer.

**Comment by Baenker** [comment]
siehe auch #630

**Comment by GermanBluefox** [comment]
Please test 1.9.2

**Comment by BRoeske** [comment]
Ok, Balkendiagramme gehen wieder mit 1.9.2 - Danke!!!
Das Problem mit dem weissen Hintergrund besteht aber immer noch. Verwendet man hellere Farben auf dunklem Hintergrund sind die Hover-Details - die ja in der Linien/Balken-Farbe angezeigt werden - nahezu unlesbar. Vorher konnte man wie bereits gesagt wenigstens über die Themen ein entsprechendes Thema mit dunklem Hover-Hintergrund auswählen. Jetzt sind alle weiss...

**Comment by GermanBluefox** [comment]
> Ok, Balkendiagramme gehen wieder mit 1.9.2 - Danke!!! Das Problem mit dem ausschliesslich weissen Hintergrund bei den Hover-Details besteht aber immer noch. Verwendet man hellere Farben auf dunklem Hintergrund sind die Hover-Details - die ja in der Linien/Balken-Farbe angezeigt werden - auf der weissen Fläche nahezu unlesbar. Vorher konnte man wie bereits gesagt wenigstens über die Themen ein entsprechendes Thema mit dunklem Hover-Hintergrund auswählen. Jetzt sind alle weiss, egal welches Thema man einstellt.

Ein Screenshot ersetzt 1000 Worte

**Comment by Apollon77** [comment]
(am besten aber in einem neuen Issue) :-)
