### ISSUE TITLE
Chart nicht sichtbar

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.echarts#7]
Chart nicht sichtbar nach update auf 0.3.8

**Screenshots & Logfiles**  

![Screenshot (2832)_LI](https://user-images.githubusercontent.com/41079106/100477760-9d546880-30e9-11eb-84ba-55544a37c995.jpg)

![Screenshot (2830)](https://user-images.githubusercontent.com/41079106/100477668-464e9380-30e9-11eb-9e19-df63471bbfb3.png)

**Versions:**  
 
Platform: Windows
RAM: 16 GB 
Node.js: v12.19.0
NPM: 6.14.8
JS Controler: 3.1.6
Admin: 4.1.11
Web: 3.0.13
Socket.io: 3.0.13
Script Engine: 4.10.5

**Comment by GermanBluefox** [comment]
Please test 0.3.9 or later

**Comment by sigi2345** [comment]
> Please test 0.3.9 or later

Ok, funktioniert mit V 0.4.0
Aber es werden keine Flot Charts mehr importiert

**Comment by GermanBluefox** [comment]
Was heißt mehr? Import passiert nur ein Mal.

**Comment by sigi2345** [comment]
> Was heißt mehr? Import passiert nur ein Mal.

ich habe leider alle Flot Charts im Adapter gelöscht.

**Comment by GermanBluefox** [comment]
Schreibe da false und reloade im Browser echarts:
![image](https://user-images.githubusercontent.com/4582016/100540950-f08cff00-3240-11eb-8ec5-6b2969a225a1.png)
