### ISSUE TITLE
[beta 1.9.2] Extrem lange Installationszeit und sehr hoher SD-Karten Speicherbedarf

### ISSUE THREAD

**Issue by Erwin40** [ioBroker/ioBroker.echarts#707]
Installation des letzten beta Releases über Katze + GitHub Link.

Die Installation hat gute 10min. benötigt.
Mir ist zwar schon schon früher aufgefallen das der Adapter etwas mehr Zeit braucht, aber noch nie so lange.

Desweiteren ist mein SD-Karten Speicherbedarf um ganze 1,8% gestiegen. (Das sind fast 1GB)
Ich habe auch schon einen kompletten Reboot des Systems durchgeführt.

Wo finde ich nun die Dateien, die ich jetzt löschen kann?

**Versions:**  
 - Adapter version: <1.9.2>
 - <html><body>

System Model | Raspberry Pi 4 Model B Rev 1.5
-- | --
CPU (Model) | ARM Cortex-A72 (3)
Distribution | Debian GNU/Linux
Release (Codename) | 12 (bookworm)
SysOpensslLib | OpenSSL
OpenSSL Ver. | 3.0.13+quic
Kernel Ver. | 6.1.21-v8+
Node.js Ver. | 20.17.0
V8 JavaScript Ver. | 11.3.244.8 (Node).23
NPM Ver. | 10.8.2

</body>
</html>

**Additional context**

**Comment by Apollon77** [comment]
Warum nimmst DU an das das ein Fehler ist? Dauer kann mit Download und SD geschwindigkeit zusammenhängen. Speicherbedarf eines Adapters kann so hoch sein, ja ...

**Comment by Apollon77** [comment]
PS: Welcher js.controller wird verwendet?

**Comment by Erwin40** [comment]
Na ja, alle anderen Adapter (17 bis jetzt) haben max. eine Minute gebraucht, bisher.
Ich habe so ziemlich die schnellste SD-Karte drin.
Und Download habe ich max. ~70MB
6.0.11
Ich bin immer ziemlich up2date :-)

Wie gesagt, bei Adapter-Updates war es bisher so, dass kaum mehr Speicher nötig war.
Und bei Jarvis und Roborock bin ich auch laufend am Beta testen.

**Comment by Apollon77** [comment]
Najs die JS Files davon brauchen halt den Platz :-)

**Comment by Erwin40** [comment]
Sorry, das verstehe ich nicht.
Es hat sich um ein Update gehandelt!
Warum sollte das jetzt plötzlich 1GB mehr Platz benötigen?

**Comment by GermanBluefox** [comment]
Der Adapter ist 160Mb gross:
![image](https://github.com/user-attachments/assets/ba4ed99e-edf1-4cc6-baf1-9231959b4550)

Es ist unklar woher 1gb gekommen ist

**Comment by Erwin40** [comment]
Genau, dass ist ja das Problem.
Ich mag es nicht besonders, wenn mein System vollgemüllt wird ;-)
Unabhängig davon, dass es die SD-Karte unnötig belastet.
Da macht beta testen keinen Spaß mehr :-)

**Comment by Erwin40** [comment]
Natürlich nicht.
Aber ich kenne Programmierer, da ich schon seit sehr langer Zeit auch als Programmierer arbeite.
Ich kenne da meine Pappenheimer. Da wird sich ausgetobt und ohne regelmäßig aufzuräumen. 
Denn Speicherplatz kostet ja nix mehr, im Gegensatz zu den Anfangszeiten.

Es war hier sicher nicht persöhnlich gemeint, sondern als Hinweis, dass man dem nachgehen sollte.
Und vielleicht ist es auch schon anderen aufgefallen. Die Info würde mich dann auch interessieren.
Ja, und sorry, wegen der ausdrucksweise "zugemüllt". Mir viel kein besseres Wort ein ;-)
Wenn mich der Rappel packt, probiere ich mal ein Update auf meiner Test SD-Karte mit vorher / nachher Vergleich der Snap-Shots.

Kann denn niemand die extrem lange Installationszeit bestätigen?

PS: Aber schon interessant, dass auf solche Beiträge umgehend reagiert wird 😁
Das der Adapter aber seit geraumer Zeit massive Probleme mit der Zeitscala hat, sollte in diesem Zusammenhang nicht unbeachtet bleiben.
Sorry das ich das jetzt so sagen muss, in einer Zeit wo Kritik gar nicht so gerne gesehen wird.
Aber der Adapter ist eigentlich echt was tolles 👍  und dann hakt es an (aus Anwendersicht) so einer "Kleinigkeit".

**Comment by Erwin40** [comment]
Hmm, gerade durch Zufall gesehen:
https://github.com/ioBroker/ioBroker.echarts/issues/470#issuecomment-1888967953

So ganz neu ist der Speicherhunger also nicht. Somit kann es eigentlich auch nicht an der iob Architektur liegen.

**Comment by Apollon77** [comment]
Also der reine Adapter (und das sind die Files die Bluefox oben genannt hat) werden aufgeräumt. Das flag in der io-package ist gesetzt und deswegen hatte ich nach dem js-controller gefragt  Damit bleibt nur die Blckbox "NPM tree und cache" übrig
