### ISSUE TITLE
Beschreibung für Typ fehlt...

### ISSUE THREAD

**Issue by DerDoubleD** [ioBroker/ioBroker.echarts#71]
**Describe the bug**  
Beschreibung für Typ fehlt...

**Expected behavior**  
Was bewirken die verschiedenen Typen?
minmax
min
max
mittel
total
roh

**Versions:**  
 - Adapter version: 1.0.3
 - JS-Controller version: 3.3.18
 - Node version: v14.18.1
 - Operating system: linux

**Comment by Apollon77** [comment]
ich denke min, max, mittel (average), total (summe), roh (rohdaten ohne aggregation) sind klar oder? minmax ist eine art derdarstelltung die versucht min und max in einem zeitinterval sichbar zu machen ... (ich kann es nicht besser beschreiben)

**Comment by DerDoubleD** [comment]
Theoretisch ja, aber
Bei mir wird nur was angezeigt wenn ich "minmax" oder "roh" ausgewählt habe.
Deshalb bin ich davon ausgegangen das ich die Bedeutung von Typ nicht verstanden habe.
Zumindest bei "mittel" müsste doch was angezeigt werden.

**Comment by uelpenich** [comment]
minmax ist dann interessant / sinnvoll, wenn in der Historiendatenbank mehr Abtastpunkte abgespeichert sind als Pixel in der Darstellung zur Verfügung stehen. Bei Mittelwert sieht man keine Streuung (min und max Wert) des Messwertes.
