### ISSUE TITLE
eigenen Datenpunkt in EChart-VisWidget  einbinden  ?!

### ISSUE THREAD

**Issue by djmarc75** [ioBroker/ioBroker.echarts#72]
Erstmal danke für den tollen Adapter.
Ich würde gerne einen eigenen Datenpunkt im EChart-VIS-Widget (EChart-ID) auswählen wollen.
Grund: eine bequeme Auswahl im VIS-Frontend der einzelnen ECharts.
Den eigenen Datenpunkt würde ich dann mit dem jeweiligen EChart als Binding befüllen.
Wäre sowas machbar ?
Merci und Grüße

**Comment by uelpenich** [comment]
Habe ich auch vermisst. 
Man kann diese Funktionalität ganz eingach mit Hilfe des Widgets "iFrame8" realisieren. Der Nachteil ist, dass man das Chart als URL angeben muss, und nicht als Pull-Down aus der Liste der Charts auswählen kann. 
Ein weiterer Nachteil in beiden Lösungen ist, dass der Datenpunkt global definiert ist. Das heisst, wenn mehrere Clients gleichzeitig visualisieren zeigen alle das gleiche Chart an. Wer zuletzt auswählt, gewinnt. 

Frage: hat jemand einen Vorschlag, wie man einen Datenpunkt abhängig vom visualisierenden Client machen kann?
![grafik](https://user-images.githubusercontent.com/63613798/146670313-d8c3c685-c348-4dd2-b43a-0e88eecfb918.png)

**Comment by djmarc75** [comment]
Die iFrame Variante ist eine gute Lösung.... werde ich umsetzen !
Auf Deine Frage wegen den verschiedenen Clients einzugehen.... leider müsstes Du für jeden Client eine separate VIS anlegen.... sehr speicherinteniv ...
Grüße

**Comment by djmarc75** [comment]
@uelpenich 
Andere Lösung wäre Folgendes:
Du duplizierst die jeweilige View mit eindeutigem Namen (z.B. eChart_TabletX, eChart_TabletY, ...).
Wenn Du diese View jetzt an Gerät X auswählen möchtest hat vis.0 Datenpunkte welche man beschreiben kann.

vis.0.control.data             (Name der View)
vis.0.control.instance       (ID des Clients)
vis.0.control.command    (Command um den Viewwechsel auszuführen "changeView")

Wenn Du nun am Client die eChart-View auswählst dann kannst Du per Skript (ich habs mit Blockly gelöst) die Datenpunkte mit den nötigen Werten beschreiben. Wichtig hierbei ist dass vis.0.control.command ("changeView" mit einer kurzen Verzögerung zu den anderen beiden Datenpunkten beschrieben wird.

Hoffe ich hab das verständlich rübergebracht.

Grüßle
