### ISSUE TITLE
Factor to multiply values with

### ISSUE THREAD

**Issue by Signum** [ioBroker/ioBroker.echarts#75]
I would like to multiply values by a certain factor.

Example:
![image](https://user-images.githubusercontent.com/36562/149626824-1fe65086-313a-41ba-b006-29e0057cb8f6.png)

This is a graph showing the eletric power flow at home between my photovoltaic system, the house, the public network and the battery. However I would like to plot energy consumption *above* the X axis and energy generation *below* the X axis. Using energy (blue graph) is shown above the X axis as well as energy generated from the solar panels (yellow graph). I thought that I would just multiply the yellow values by "-1" to move them to the other side of the X axis but I failed to find such a setting.

And of course thanks so much for the adapter. The charts work and look awesome.

**Comment by miege2k** [comment]
I have the same issue. For help I would be very grateful.

**Comment by uelpenich** [comment]
Workaround: 
Use an alias or a device manager to calculate the value multiplied by the intended factor. 
You can also use special y-axis min and max value together with y-offset to get similar effects.

**Comment by GermanBluefox** [comment]
In 1.3.4 you can define the Formula:
![image](https://user-images.githubusercontent.com/4582016/217640252-b6faeeb4-96ad-4119-9fc7-eecc1d2213a1.png)

**Comment by Signum** [comment]
@GermanBluefox Thanks a lot. That's great news. Will version 1.3.4 be made available through the beta channel?

**Comment by Apollon77** [comment]
1.3.4 was released yesterdaay evening and should appear today in Beta channel
