### ISSUE TITLE
Bei 2 X-Achsen stehen Werte übereinander

### ISSUE THREAD

**Issue by WernerSch** [ioBroker/ioBroker.echarts#77]
**Describe the bug**  
Wenn ich 2 X-Achsen anlege stehen die Werte übereinander bzw. überschreiben sich gegensetig

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![grafik](https://user-images.githubusercontent.com/22211324/151713532-8010d2c5-58f8-46a9-86db-f226de3a1d2a.png)

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by uelpenich** [comment]
Bug / Enhancement is identical  to:
Multiple-Y-Axis enhancement
#42 opened on 2 May 2021 by uelpenich
