### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.echarts#8]
I'm having problems embedding in an iframe.  

If the background of the chart is specified in rgba (0, 0, 0, 0), no transparent white background is displayed in the iframe.  
That would make sense if you don't use a VIS with a widget.  For example I use lovelace.  
At the moment I am incorporating the charts via flot.  That also works with transparency.

Here is a picture to illustrate the problem with my bad English:
Flot vs echart
![Screenshot_20201128-085514_Fully Kiosk Browser](https://user-images.githubusercontent.com/66136363/100496838-b85dc180-3157-11eb-90a3-7db9d9dcf835.jpg)

**Comment by GermanBluefox** [comment]
Please use "No background" option in next version (0.4.0)
![image](https://user-images.githubusercontent.com/4582016/100516919-82383600-3187-11eb-9d58-ce28d46ed33a.png)

**Comment by ipod86** [comment]
Very cool.  Thank you.
