### ISSUE TITLE
Does not start anymore

### ISSUE THREAD

**Issue by jheisel01** [ioBroker/ioBroker.echarts#81]
Hi,
the Echarts Adapter does not start anymore, it worked in the past.

**Describe the bug**  
The Adapter does not start, after clicking Echarts, screen will be empty, without any Error message in Log files,

**To Reproduce**  
1. Go to Admin Gui (5.3.1)
2. Click on eCharts
3. - empty screen 

**Versions:**  
 - Adapter version: <1.0.3>
 - JS-Controller version: <3.3.22> 
 - Node version: <v14.18.3> 
 - Operating system: <debian 10.11>

**Additional context**  
Deinstall Adapter, reboot, install adpater - does not start

**Comment by Apollon77** [comment]
Please look into browser console when "Page is empty" ... And post the show error message

**Comment by jheisel01** [comment]
Hi,
I did the following steps and it works again:
Remove echarts Adapter, update the Debian OS, reboot the Host, install the Adapter and it worked again.
I don*t know why, because I tried this several times before.
