### ISSUE TITLE
[solved in expert modus]object of older preset is missing as entry in iobroker.objects (#45 hints to a solution)

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.echarts#82]
Hi, 

in iobroker.objects.echarts ther are some presets as objects, great.
when I add (+) a new (=empty) preset it is also shown as object in iobroker objects - perfect!

but some old presets are NOT objects in iobroker objects, they just "work". Looks to me, that they have been created before the "objects" functionality. Also when I copy these old presets inside the echarts-gui the copy is also no (new) object.

All these old presets can be modified, saved, viewed as chart, even copied, but never create objects as the "new" presets do.

Is there any chance to get objects from these "old" presets?

I created a lot of presets in the beginning of echarts and really would love to have them as objects, as some characteristics are not editable in the echart-gui as smaller levels of filling (e.g. 0.3), sometimes I only want change name of sensor (which is easy in editing the object with copy, edit copied object, save, rename preset ...)
It is a lot of work to manually create new objects from old presets and get all the fine tuned values into a new preset.

Thank You for looking into this
Harvey

**Comment by harvey637** [comment]
Hi, I found something in  #45

looks like "old" presets have the attribute "export" in it.
Removed this and they appear in non_expert view.

So this could be manually solved by removing all expert-settings in the objects.

Still unclear why this happended, but no problem now.

Maybe a hint to this problems and solution might be published in readme.md ....
cu
Harvey

**Comment by Apollon77** [comment]
Pleas ebe more specific, show screenshots, onbject sdefinitions and such ...

**Comment by harvey637** [comment]
Hi, thx for looking into this ...
as found in #45 some older echarts are marked with "expert=true" modus, so they only show up when in export modus.
newer presets are saved without this expert=true attribute so they are always visible.

My "problem" is solved for me, as I edited all my old presets in expert modus and removed the line "expert=true,", then saved.
Now all presets are ok also in noon expert modus.

This kind of solved my other problem, the one with moving between subfolders:
create new preset in target-folder, open edit on source-preset, copy everything in "native ...", paste into freshly created target-preset, rename new preset, remove old preset.

But a "move to other folder" button might be handy :-)
thx and cu
Harvey

**Comment by Apollon77** [comment]
aahhh ok, then it was a typo above ... export !== expert :-)

**Comment by harvey637** [comment]
solved by "move" button - fixed!!
