### ISSUE TITLE
moving existing presets between folders or between subfolders

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.echarts#84]
Hi,
subfolders in presets are a good way to organize presets, e.g. all presets related to photovoltaic.

but I found no way to move existing presets between folders :-(

Is this missing or am I too blind to see?

Renaming a preset and adding the subfolder does not work, dot is transformed into underscore.

Thank you
Harvey

**Comment by harvey637** [comment]
Hi,
a manual way to "move" into a new subfolder:

create new preset in target-folder, open edit on source-preset, copy everything in "native ...", paste into freshly created target-preset, rename new preset, remove old preset.

But a "move to other folder" button might be handy :-)
cu
Harvey

**Comment by GermanBluefox** [comment]
Hm....
![echart1](https://user-images.githubusercontent.com/4582016/218701100-2a764399-240b-488b-a65f-45f28437343d.gif)

**Comment by harvey637** [comment]
working! Thank You
