### ISSUE TITLE
Nachkommastellen selbst festlegen

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.echarts#86]
![image](https://user-images.githubusercontent.com/84818934/166112784-aa33636a-3939-48e5-84af-4d765bee0f00.png)
Die Min und Maxwerte werden mit zu vielen Nachkommastellen angezeigt.
Wenn möglich, eine Option einbauen, mit der man selber die Anzahl der Nachkommstellen für alle Werte festlegen kann.
Danke.

**Comment by uelpenich** [comment]
Die Möglichkeit besteht bereits: 
Bei den Datenquellen kann man die Ziffern nach dem Komma angeben, sowie manuell den Min und Max Wert der Y-Ache vorgeben. 
![grafik](https://user-images.githubusercontent.com/63613798/166140492-5a9f62f6-fe5a-41e1-baa0-44c853ccc806.png)
