### ISSUE TITLE
No instance is shown

### ISSUE THREAD

**Issue by Chookees** [ioBroker/ioBroker.echarts#89]
When clicking on Instance for example on Line1, are there no instances shown and i guess therefore i can't select any ID (is empty when looking at view).
![image](https://user-images.githubusercontent.com/24595815/167927332-74c2f867-5013-4d77-bd00-fd78d08e2071.png)
![image](https://user-images.githubusercontent.com/24595815/167927370-9c603d4e-cbfb-4a72-852d-e73643b65cf3.png)

Already tried downgrading the Version to 1.0.2, did not help

**Comment by GermanBluefox** [comment]
Do yo have any RUNNING instance of history, sql or influxdb?
