### ISSUE TITLE
Enable InfluxDB2 tag support 

### ISSUE THREAD

**Issue by jpawlowski** [ioBroker/ioBroker.echarts#95]
InfluxDB 2.x supports tagging which can be enabled on the `iobroker.influxdb` adapter as described [here](https://github.com/ioBroker/ioBroker.influxdb/blob/master/README.md#Store-metadata-information-as-tags-instead-of-fields).
However, it seems the queries that ECharts uses are incompatible as no data can be retrieved, resulting in empty charts.

Could this be implemented?

**Comment by Apollon77** [comment]
ECharts is using getHistory calls, so please open this issue in InfluxDB adapter.

Please enable extended debug log for one example datapoint with a new 3.x Influxdb version(Beta repository) and also change the loglevel of the influxdb instance to debug. Attach that log from such a echarts request (getHistory)
