### ISSUE TITLE
Invalide Namespace

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.echarts#96]
Hallo,

nach Update auf 1.0.9 funktioniert es nicht mehr. 

![Screenshot (4973)](https://user-images.githubusercontent.com/41079106/174266992-98307253-c34c-4eac-897a-4f3443eaf617.png)
![Screenshot (4974)](https://user-images.githubusercontent.com/41079106/174267185-81924846-6973-4a88-939c-990ea961a37a.png)
Plattform: Windows
RAM: 16 GB 
NODE.JS: V16.5.1
NPM: 8.11.0
JS Controller: 4.0.23
Admin: 6.0.4
WS: 2.1.0
WEB: 5.2.0
Socket.io: 6.1.3
Script Engine: 5.7.0
IOT: 1.11.4
VIS: 1.4.15

**Comment by Baenker** [comment]
Habe das gleiche Problem.

**Comment by jlegen** [comment]
Habe vermutlich das gleiche Problem, allerdings in Verbindung mit iqontrol. echart-Diagramme scheinen seit 1.0.9 nicht mehr über den Web-Adapter (Port 8082) abrufbar zu sein, sondern nur noch über den Admin-Port (8081)…

**Comment by Horgul123** [comment]
Kann das Problem leider auch bestätigen :(

**Comment by ykuendig** [comment]
Die Fehlermeldung (1.0.9) beim echart iframe ist zwar weg. Die Grafik lädt aber trotzdem nicht (mit 1.0.10). Mit 1.0.8 gehts.

**Comment by Grothesk242** [comment]
Muss aber was mehr oder weniger individuelles sein. Hier funktionieren z. B. beide Ports, 8081 und 8082.

**Comment by beandi** [comment]
Im Browser direkt ging es schon immer ohne Probleme, nur als Einbindung (iFrame) in Jarvis oder iqontrol geht es seit 1.0.9 nicht - deshalb bin ich auch noch auf 1.0.8

**Comment by jlegen** [comment]
mit 1.3.4 besteht das Problem leider immer noch, Browser sagt:

Request URL: https://10.10.10.250:8082/adapter/echarts/chart/socket.io/?ws=true&EIO=3&transport=polling&t=OP1jDDp
Request Method: GET
Status Code: 404 Not Found
Referrer Policy: strict-origin-when-cross-origin

Console:
GET https://10.10.10.250:8082/adapter/echarts/chart/socket.io/?ws=true&EIO=3&transport=polling&t=OP1nFbi 404 (Not Found)
(anonymous) @ trycatch.ts:179
(anonymous) @ instrument.ts:286
i.create @ socket.io.js:7
i @ socket.io.js:7
o.request @ socket.io.js:7
o.doPoll @ socket.io.js:7
r.poll @ socket.io.js:7
r.doOpen @ socket.io.js:7
r.open @ socket.io.js:7
r.open @ socket.io.js:6
r @ socket.io.js:6
r @ socket.io.js:6
r.open.r.connect @ socket.io.js:6
r @ socket.io.js:6
r @ socket.io.js:6
r @ socket.io.js:6
(anonymous) @ Connection.ts:288
v @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:125
(anonymous) @ regeneratorRuntime.js:69
e @ asyncToGenerator.js:3
i @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ Connection.ts:423
(anonymous) @ Connection.ts:110
Promise.then (async)
t @ Connection.ts:110
o @ App.js:110
Ic @ react-dom.production.min.js:147
Li @ react-dom.production.min.js:198
Ss @ react-dom.production.min.js:292
xl @ react-dom.production.min.js:280
gl @ react-dom.production.min.js:280
zl @ react-dom.production.min.js:280
cl @ react-dom.production.min.js:268
H @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
instrument.ts:124 
Connect error: Error: xhr poll error

**Comment by GermanBluefox** [comment]
> mit 1.3.4 besteht das Problem leider immer noch, Browser sagt:
> 
> Request URL: https://10.10.10.250:8082/adapter/echarts/chart/socket.io/?ws=true&EIO=3&transport=polling&t=OP1jDDp Request Method: GET Status Code: 404 Not Found Referrer Policy: strict-origin-when-cross-origin
> 

Was passiert wenn man statt 
`https://10.10.10.250:8082/adapter/echarts/chart/index.html?preset=XXX`

`https://10.10.10.250:8082/echarts/index.html?preset=XXX` aufruft?

Wie ist die Adresse `https://10.10.10.250:8082/adapter/echarts/chart/index.html` entstanden?

**Comment by jlegen** [comment]
> 
> Was passiert wenn man statt `https://10.10.10.250:8082/adapter/echarts/chart/index.html?preset=XXX`
> 
> `https://10.10.10.250:8082/echarts/index.html?preset=XXX` aufruft?

sowohl mit 1.0.8, als auch mit 1.3.4: 
"File index.html not found"

> 
> Wie ist die Adresse `https://10.10.10.250:8082/adapter/echarts/chart/index.html` entstanden?

das ist einfach die URL, die man beim Klick in Echarts auf "Diagramm in eigenem Fenster öffnen" erhält ( "[ ]").

Diese ist bei 1.0.8 und 1.3.4 identisch - *aber* - das ist mir erst jetzt gerade aufgefallen: Nach dem Update auf 1.3.4 ist meine "EChart-Auswahl" komplett verschwunden, es wird nur noch der "Influxdb-Ordner" mit den einzelnen Datenpunkten gelistet. 

Allerdings "überlebt" der jeweils zuletzt unter 1.0.8 benutzte Chart (hier: "Temperaturen Innen") den Adapterwechsel auf 1.3.4, daher war mir das nicht sofort aufgefallen. Aber möglicherweise rührt daher ja das eigentliche Problem?

Vorher/1.0.8:

![grafik](https://user-images.githubusercontent.com/24507951/218505067-6a8ea600-689a-4cbf-9fdc-b5960825ea8a.png)

Nachher/1.3.4:

![grafik](https://user-images.githubusercontent.com/24507951/218505166-9837614c-df92-4b69-83b1-b656723348dd.png)

**Comment by GermanBluefox** [comment]
> sowohl mit 1.0.8, als auch mit 1.3.4:
> "File index.html not found"

Das kann nicht sein:
![image](https://user-images.githubusercontent.com/4582016/218691809-c0a8b7c5-4cdf-43f2-8f5f-6138c6ece26c.png)

Dann ist was kaputt. `iob u echarts` ausführen und dann F5. Hilft?

**Comment by GermanBluefox** [comment]
> das ist einfach die URL, die man beim Klick in Echarts auf "Diagramm in eigenem Fenster öffnen" erhält ( "[ ]").

Das glaube ich auch nicht. Vermutlich hat man manuell 8081 durch 8082 ersetz. Um Web Link zu bekommen bitte diese Buttons benutzen:
![image](https://user-images.githubusercontent.com/4582016/218693221-0f5376f4-0d0e-4ade-93f1-59ec86246620.png)

**Comment by GermanBluefox** [comment]
> Nach dem Update auf 1.3.4 ist meine "EChart-Auswahl" komplett verschwunden,

Ist echarts Instanz gestarted?

**Comment by Apollon77** [comment]
@jlegen 
> Cannot find search "chart" in "system"
Das ist dann eine alte version ... oder irgendwie alter "code" ... die aktuellen Fragen chart/chart ab und das exsitiert.

**Comment by jlegen** [comment]
> @jlegen
> 
> > Cannot find search "chart" in "system"
> > Das ist dann eine alte version ... oder irgendwie alter "code" ... die aktuellen Fragen chart/chart ab und das exsitiert.

was meinst du hier mit "alter Version"? Wie gesagt, mit der "alten Version" 1.0.8 funktioniert alles tutti - nach dem Upgrade auf 1.3.4 (oder auch 1.2.1) ist die Auswahl im Admin weg, und o.g. Fehler zeigen sich.

K.A. was "alter Code" sein könnte - ich habe die Charts ja nicht "codiert", sondern in 1.0,8 angelegt. Sorry, JS/Node ist leider ein blinder Fleck bei mir ;-)

Rest vom System ist jedenfalls aktuell (Admin 6.3.6, JS-Ctrl 4.0.24)...

**Comment by Bernd9000** [comment]
@jlegen 
> TypeError: Br is undefined Gr ChartOption.js:289 

Den Fehler hatte ich auch, siehe [#255](https://github.com/ioBroker/ioBroker.echarts/issues/255#issuecomment-1429961920)
 Lag vermutlich am Fill Wert.
Fehler ist seit Version v1.4.3 erledigt

**Comment by jlegen** [comment]
> @jlegen
> 
> > TypeError: Br is undefined Gr ChartOption.js:289
> 
> Den Fehler hatte ich auch, siehe [#255](https://github.com/ioBroker/ioBroker.echarts/issues/255#issuecomment-1429961920) Lag vermutlich am Fill Wert. Fehler ist seit Version v1.4.3 erledigt

tatsächlich ist *dieser* Fehler mit 1.4.3 auch bei mir behoben - es bleibt aber bei 'Error: Cannot find search "chart" in "system"', und einer leeren Chartauswahl im Echarts-Admin 😞 
(wobei alle "alten" Charts aber auch unter 1.4.3 dargestellt werden, wenn man die Chart-URLs direkt anspricht - editieren geht halt nicht)

**Comment by jlegen** [comment]
die Erwähnung oben von "altem Zeug" 😉  hat mich jetzt mal den echarts.0-Objektbaum exportieren lassen. Danach habe ich die echarts-Instanz (1.0.8) gelöscht, und den Adapter auf 1.4.3 aktualisiert.
Dann habe ich den alten Objektbaum wieder importiert - und was soll ich sagen, das Ding läuft! 👍
