### ISSUE TITLE
not possible to generate charts on your Hardware/OS

### ISSUE THREAD

**Issue by Merexor** [ioBroker/ioBroker.echarts#99]
**Describe the bug**  
Auf Telegram würde ich mir die Charts schicken, was bis jetzt immer gut funktioniert hat.
Leider funktioniert in letzter Zeit das generieren nicht mehr.

Telegram Meldung
Cannot find required modules: looks like it is not possible to generate charts on your Hardware/OS.

ioBroker Log:
Cannot find required modules: Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'was compiled against a different Node.js version usingNODE_MODULE_VERSION 72. This version of Node.js requiresNODE_MODULE_VERSION 83. Please try re-compiling or re-installingthe module (for instance, using `npm rebuild` or `npm install`)

**To Reproduce**  
on({id: "telegram.0.communicate.request", change: "any"}, async (obj) => {
    if (obj.state.val.indexOf('Dia-Serverauslastung') > -1) { 
        sendChart();     
    }
});

function sendChart() {
    sendTo('echarts.0', {
    preset:   'echarts.0.Technik.Server',
    renderer: 'png',
    background: '#FFFFFF',
    theme: 'light',
    quality: 1.0,
    compressionLevel: 5,
    filters: 1, 
    fileOnDisk: '/opt/iobroker/iobroker-data/echarts-temp-photo.jpg'
}, result => {
    if (result.error) {
        sendTo("telegram.0", "send", { text: result.error });
    } else {
        sendTo("telegram.0", "send", { text: '/opt/iobroker/iobroker-data/echarts-temp-photo.jpg'  });
    }
});
}

**Versions:**  
 - Adapter version: <v1.0.7>
 - JS-Controller version: <4.0.23> 
 - Node version: <v14.19.3>
 - Operating system: <Intel Noc ( Proxmox )>

**Comment by Apollon77** [comment]
Go on the host and execute:

```
cd /opt/iobroker/node_modules/canvas
npm install
```

This should fix it

**Comment by Merexor** [comment]
Hat leider nichts gebracht ...

**Comment by Merexor** [comment]
root@ioBroker:~# cd /opt/iobroker/node_modules/canvas
root@ioBroker:/opt/iobroker/node_modules/canvas# npm install
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> canvas@2.9.1 install /opt/iobroker/node_modules/canvas
> node-pre-gyp install --fallback-to-build

[canvas] Success: "/opt/iobroker/node_modules/canvas/build/Release/canvas.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
added 481 packages from 712 contributors and audited 484 packages in 13.594s

51 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 moderate, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
root@ioBroker:/opt/iobroker/node_modules/canvas# npm audit fix
up to date in 1.466s

51 packages are looking for funding
  run `npm fund` for details

fixed 0 of 2 vulnerabilities in 484 scanned packages
  1 package update for 2 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │     New major version of npm available! 6.14.17 -> 8.13.2      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v8.13.2   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

root@ioBroker:/opt/iobroker/node_modules/canvas# exit      
logout

Ubuntu 21.10 ioBroker tty1

ioBroker login: root
Password: 
Welcome to Ubuntu 21.10 (GNU/Linux 5.13.19-4-pve x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Tue Jul  5 18:29:31 UTC 2022 on tty1
root@ioBroker:~# iobroker -v
4.0.23
root@ioBroker:~# node -v
v14.19.3
root@ioBroker:~# cd /opt/iobroker/node_modules/canvas
root@ioBroker:/opt/iobroker/node_modules/canvas# npm rebuild
simple-get@3.1.1 /opt/iobroker/node_modules/canvas/node_modules/simple-get
decompress-response@4.2.1 /opt/iobroker/node_modules/canvas/node_modules/decompress-response
mimic-response@2.1.0 /opt/iobroker/node_modules/canvas/node_modules/mimic-response
root@ioBroker:/opt/iobroker/node_modules/canvas#

**Comment by klein0r** [comment]
> This should fix it

Maybe it's better to execute that in the context of the iobroker user (to keep file permissions correctly)

`sudo -u iobroker npm install`
